# BitBrains — Workload & Resource Telemetry EDA

## Objective

This notebook performs exploratory data analysis on the BitBrains
workload/resource telemetry dataset.

The objectives are to:

- Understand the structure and schema of the BitBrains dataset
- Inspect VM workload activity
- Analyze CPU, memory, disk, and network utilization
- Validate timestamps and telemetry records
- Identify missing and duplicated observations
- Analyze VM/resource behavior over time
- Construct workload-level summary features
- Produce an analysis-ready telemetry dataset

## Role in the FinOps Platform

BitBrains is treated as an auxiliary workload/resource telemetry
dataset.

It is NOT used as the primary financial ground truth.

FOCUS 1.0 provides actual cloud expenditure, while BitBrains
provides workload and resource utilization context.

## Resources

In [ ]:
import os
from pathlib import Path

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_rows", 100)
pd.set_option("display.width", 140)

RANDOM_STATE = 42

print("Libraries imported successfully.")

Libraries imported successfully.

In [ ]:
from google.colab import drive

drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
from pathlib import Path

DRIVE_ROOT = Path("/content/drive/MyDrive")

BITBRAINS_DIR = DRIVE_ROOT / "fastStorage" / "2013-8"

print("BitBrains directory:")
print(BITBRAINS_DIR)

print("\nExists:", BITBRAINS_DIR.exists())

BitBrains directory:
/content/drive/MyDrive/fastStorage/2013-8

Exists: True

In [ ]:
RAW_DIR = BITBRAINS_DIR

In [ ]:
uploaded = {}
COLAB_ROOT = Path('/content')

In [ ]:
bitbrains_files = sorted(
    BITBRAINS_DIR.glob("*.csv")
)

print("Total CSV files:", len(bitbrains_files))

Total CSV files: 1250

In [ ]:
total_size_gb = sum(
    file.stat().st_size for file in bitbrains_files
) / (1024 ** 3)

print(f"Total CSV files: {len(bitbrains_files)}")
print(f"Total size: {total_size_gb:.2f} GB")

Total CSV files: 1250
Total size: 1.16 GB

In [ ]:
sample_files = [
    bitbrains_files[0],
    bitbrains_files[len(bitbrains_files) // 2],
    bitbrains_files[-1]
]

for file in sample_files:
    print("\n" + "=" * 80)
    print("FILE:", file.name)

    with open(file, "r", encoding="utf-8", errors="ignore") as f:
        for _ in range(3):
            print(f.readline().strip())

================================================================================
FILE: 1.csv
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	4;	11703.99824;	10912.027692426667;	93.23333333333333;	6.7108864E7;	6129274.4;	0.13333333333333333;	15981.6;	0.0;	2.1333333333333333
1376315146;	4;	11703.99824;	10890.57036232;	93.05;	6.7108864E7;	6755624.0;	1.3333333333333333;	19137.333333333332;	0.0;	2.6

================================================================================
FILE: 436.csv
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	4;	10399.997204;	168.13328813133333;	1.6166666666666665;	2185216.0;	123032.8;	0.0;	12.733333333333334;	4.8;	0.0
1376315146;	4;	10399.997204;	164.66662239666667;	1.5833333333333335;	2185216.0;	123032.8;	0.0;	12.533333333333333;	4.733333333333333;	0.0

================================================================================
FILE: 999.csv
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	4;	9599.998716;	0.0;	0.0;	522248.0;	45786.666666666664;	0.0;	0.2;	0.0;	0.0
1376315146;	4;	9599.998716;	0.0;	0.0;	522248.0;	36697.6;	0.0;	0.0;	0.0;	0.0

In [ ]:
file_sizes = pd.DataFrame({
    "file": [f.name for f in bitbrains_files],
    "size_mb": [
        f.stat().st_size / (1024 ** 2)
        for f in bitbrains_files
    ]
})

display(file_sizes.describe())

display(
    file_sizes.sort_values(
        "size_mb",
        ascending=False
    ).head(10)
)

           size_mb
count  1250.000000
mean      0.951066
std       0.234934
min       0.000781
25%       0.876549
50%       0.998173
75%       1.079884
max       1.755983

         file   size_mb
818    61.csv  1.755983
951    73.csv  1.522959
824   615.csv  1.439100
816   608.csv  1.431204
539   359.csv  1.418095
867   654.csv  1.416502
744   543.csv  1.410835
1076  842.csv  1.405258
535   355.csv  1.402313
1037  807.csv  1.399149

In [ ]:
import shutil

for filename in uploaded.keys():
    source = COLAB_ROOT / filename
    destination = RAW_DIR / filename

    shutil.move(
        str(source),
        str(destination)
    )

print("Files in BitBrains raw directory:")

for file in RAW_DIR.iterdir():
    print(" -", file.name)

Files in BitBrains raw directory:
 - 1234.csv
 - 138.csv
 - 1207.csv
 - 1250.csv
 - 1241.csv
 - 1239.csv
 - 1202.csv
 - 139.csv
 - 143.csv
 - 1201.csv
 - 1194.csv
 - 1186.csv
 - 1205.csv
 - 120.csv
 - 1218.csv
 - 1198.csv
 - 118.csv
 - 1178.csv
 - 1182.csv
 - 1188.csv
 - 1220.csv
 - 1174.csv
 - 1230.csv
 - 1222.csv
 - 1181.csv
 - 146.csv
 - 1203.csv
 - 140.csv
 - 1210.csv
 - 13.csv
 - 1180.csv
 - 1197.csv
 - 1217.csv
 - 127.csv
 - 1209.csv
 - 141.csv
 - 1196.csv
 - 131.csv
 - 1192.csv
 - 1216.csv
 - 1248.csv
 - 1223.csv
 - 1229.csv
 - 1221.csv
 - 1191.csv
 - 137.csv
 - 14.csv
 - 1185.csv
 - 1245.csv
 - 1214.csv
 - 1183.csv
 - 1228.csv
 - 135.csv
 - 1179.csv
 - 227.csv
 - 196.csv
 - 219.csv
 - 199.csv
 - 156.csv
 - 237.csv
 - 203.csv
 - 158.csv
 - 224.csv
 - 172.csv
 - 232.csv
 - 19.csv
 - 211.csv
 - 230.csv
 - 168.csv
 - 175.csv
 - 159.csv
 - 162.csv
 - 209.csv
 - 205.csv
 - 214.csv
 - 220.csv
 - 226.csv
 - 216.csv
 - 223.csv
 - 148.csv
 - 15.csv
 - 151.csv
 - 204.csv
 - 234.csv
 - 194.csv
 - 173.csv
 - 152.csv
 - 183.csv
 - 206.csv
 - 20.csv
 - 222.csv
 - 180.csv
 - 201.csv
 - 187.csv
 - 176.csv
 - 169.csv
 - 163.csv
 - 184.csv
 - 160.csv
 - 164.csv
 - 190.csv
 - 186.csv
 - 149.csv
 - 21.csv
 - 212.csv
 - 221.csv
 - 179.csv
 - 195.csv
 - 171.csv
 - 16.csv
 - 166.csv
 - 197.csv
 - 155.csv
 - 236.csv
 - 22.csv
 - 185.csv
 - 202.csv
 - 189.csv
 - 210.csv
 - 235.csv
 - 147.csv
 - 233.csv
 - 157.csv
 - 217.csv
 - 154.csv
 - 193.csv
 - 182.csv
 - 177.csv
 - 23.csv
 - 174.csv
 - 161.csv
 - 208.csv
 - 150.csv
 - 228.csv
 - 181.csv
 - 2.csv
 - 167.csv
 - 188.csv
 - 215.csv
 - 191.csv
 - 153.csv
 - 18.csv
 - 238.csv
 - 198.csv
 - 213.csv
 - 229.csv
 - 225.csv
 - 200.csv
 - 170.csv
 - 231.csv
 - 192.csv
 - 17.csv
 - 165.csv
 - 218.csv
 - 178.csv
 - 207.csv
 - 251.csv
 - 283.csv
 - 305.csv
 - 329.csv
 - 284.csv
 - 266.csv
 - 269.csv
 - 293.csv
 - 294.csv
 - 272.csv
 - 303.csv
 - 313.csv
 - 319.csv
 - 256.csv
 - 267.csv
 - 290.csv
 - 252.csv
 - 257.csv
 - 321.csv
 - 315.csv
 - 323.csv
 - 281.csv
 - 287.csv
 - 3.csv
 - 248.csv
 - 322.csv
 - 26.csv
 - 277.csv
 - 260.csv
 - 307.csv
 - 292.csv
 - 330.csv
 - 326.csv
 - 320.csv
 - 295.csv
 - 29.csv
 - 325.csv
 - 286.csv
 - 278.csv
 - 270.csv
 - 32.csv
 - 304.csv
 - 33.csv
 - 240.csv
 - 316.csv
 - 276.csv
 - 288.csv
 - 328.csv
 - 27.csv
 - 282.csv
 - 255.csv
 - 241.csv
 - 259.csv
 - 254.csv
 - 291.csv
 - 324.csv
 - 243.csv
 - 327.csv
 - 279.csv
 - 306.csv
 - 249.csv
 - 274.csv
 - 250.csv
 - 268.csv
 - 289.csv
 - 317.csv
 - 264.csv
 - 239.csv
 - 311.csv
 - 302.csv
 - 271.csv
 - 30.csv
 - 258.csv
 - 300.csv
 - 25.csv
 - 28.csv
 - 263.csv
 - 275.csv
 - 265.csv
 - 262.csv
 - 285.csv
 - 331.csv
 - 309.csv
 - 31.csv
 - 297.csv
 - 242.csv
 - 280.csv
 - 299.csv
 - 301.csv
 - 244.csv
 - 308.csv
 - 246.csv
 - 261.csv
 - 310.csv
 - 24.csv
 - 247.csv
 - 296.csv
 - 314.csv
 - 312.csv
 - 253.csv
 - 318.csv
 - 298.csv
 - 273.csv
 - 245.csv
 - 346.csv
 - 376.csv
 - 373.csv
 - 393.csv
 - 359.csv
 - 424.csv
 - 401.csv
 - 418.csv
 - 360.csv
 - 405.csv
 - 350.csv
 - 385.csv
 - 404.csv
 - 342.csv
 - 365.csv
 - 410.csv
 - 332.csv
 - 379.csv
 - 400.csv
 - 341.csv
 - 356.csv
 - 394.csv
 - 416.csv
 - 333.csv
 - 415.csv
 - 336.csv
 - 362.csv
 - 352.csv
 - 374.csv
 - 392.csv
 - 389.csv
 - 390.csv
 - 395.csv
 - 334.csv
 - 414.csv
 - 428.csv
 - 339.csv
 - 357.csv
 - 42.csv
 - 347.csv
 - 396.csv
 - 351.csv
 - 406.csv
 - 422.csv
 - 39.csv
 - 408.csv
 - 340.csv
 - 419.csv
 - 343.csv
 - 368.csv
 - 398.csv
 - 348.csv
 - 384.csv
 - 403.csv
 - 420.csv
 - 426.csv
 - 391.csv
 - 377.csv
 - 37.csv
 - 417.csv
 - 386.csv
 - 382.csv
 - 354.csv
 - 388.csv
 - 366.csv
 - 399.csv
 - 36.csv
 - 380.csv
 - 35.csv
 - 349.csv
 - 367.csv
 - 383.csv
 - 425.csv
 - 372.csv
 - 413.csv
 - 427.csv
 - 338.csv
 - 353.csv
 - 375.csv
 - 344.csv
 - 41.csv
 - 34.csv
 - 409.csv
 - 345.csv
 - 378.csv
 - 402.csv
 - 355.csv
 - 411.csv
 - 364.csv
 - 40.csv
 - 38.csv
 - 381.csv
 - 412.csv
 - 361.csv
 - 4.csv
 - 335.csv
 - 337.csv
 - 363.csv
 - 358.csv
 - 397.csv
 - 407.csv
 - 370.csv
 - 387.csv
 - 371.csv
 - 421.csv
 - 369.csv
 - 423.csv
 - 502.csv
 - 444.csv
 - 455.csv
 - 508.csv
 - 51.csv
 - 456.csv
 - 49.csv
 - 488.csv
 - 494.csv
 - 441.csv
 - 430.csv
 - 450.csv
 - 435.csv
 - 462.csv
 - 517.csv
 - 45.csv
 - 511.csv
 - 43.csv
 - 498.csv
 - 495.csv
 - 477.csv
 - 439.csv
 - 445.csv
 - 519.csv
 - 453.csv
 - 431.csv
 - 5.csv
 - 468.csv
 - 442.csv
 - 492.csv
 - 472.csv
 - 487.csv
 - 475.csv
 - 50.csv
 - 471.csv
 - 473.csv
 - 516.csv
 - 449.csv
 - 432.csv
 - 434.csv
 - 479.csv
 - 482.csv
 - 501.csv
 - 504.csv
 - 440.csv
 - 463.csv
 - 484.csv
 - 452.csv
 - 489.csv
 - 438.csv
 - 448.csv
 - 490.csv
 - 521.csv
 - 436.csv
 - 522.csv
 - 507.csv
 - 459.csv
 - 478.csv
 - 500.csv
 - 503.csv
 - 513.csv
 - 464.csv
 - 493.csv
 - 465.csv
 - 518.csv
 - 52.csv
 - 443.csv
 - 44.csv
 - 523.csv
 - 480.csv
 - 447.csv
 - 497.csv
 - 499.csv
 - 474.csv
 - 46.csv
 - 446.csv
 - 514.csv
 - 437.csv
 - 457.csv
 - 486.csv
 - 509.csv
 - 461.csv
 - 496.csv
 - 512.csv
 - 470.csv
 - 491.csv
 - 467.csv
 - 458.csv
 - 47.csv
 - 505.csv
 - 483.csv
 - 481.csv
 - 460.csv
 - 469.csv
 - 520.csv
 - 515.csv
 - 433.csv
 - 506.csv
 - 466.csv
 - 454.csv
 - 476.csv
 - 510.csv
 - 429.csv
 - 485.csv
 - 451.csv
 - 48.csv
 - 566.csv
 - 537.csv
 - 524.csv
 - 564.csv
 - 578.csv
 - 605.csv
 - 529.csv
 - 601.csv
 - 569.csv
 - 599.csv
 - 547.csv
 - 545.csv
 - 574.csv
 - 593.csv
 - 580.csv
 - 55.csv
 - 609.csv
 - 548.csv
 - 612.csv
 - 586.csv
 - 600.csv
 - 572.csv
 - 562.csv
 - 607.csv
 - 536.csv
 - 571.csv
 - 582.csv
 - 581.csv
 - 533.csv
 - 54.csv
 - 613.csv
 - 543.csv
 - 53.csv
 - 544.csv
 - 527.csv
 - 570.csv
 - 549.csv
 - 552.csv
 - 591.csv
 - 575.csv
 - 584.csv
 - 583.csv
 - 556.csv
 - 576.csv
 - 58.csv
 - 59.csv
 - 558.csv
 - 557.csv
 - 539.csv
 - 542.csv
 - 534.csv
 - 567.csv
 - 528.csv
 - 579.csv
 - 541.csv
 - 563.csv
 - 540.csv
 - 551.csv
 - 585.csv
 - 592.csv
 - 538.csv
 - 588.csv
 - 604.csv
 - 531.csv
 - 553.csv
 - 530.csv
 - 611.csv
 - 554.csv
 - 596.csv
 - 606.csv
 - 590.csv
 - 6.csv
 - 598.csv
 - 589.csv
 - 535.csv
 - 560.csv
 - 610.csv
 - 61.csv
 - 550.csv
 - 568.csv
 - 561.csv
 - 587.csv
 - 532.csv
 - 603.csv
 - 56.csv
 - 602.csv
 - 577.csv
 - 573.csv
 - 526.csv
 - 60.csv
 - 595.csv
 - 546.csv
 - 559.csv
 - 597.csv
 - 594.csv
 - 565.csv
 - 608.csv
 - 57.csv
 - 555.csv
 - 525.csv
 - 643.csv
 - 696.csv
 - 637.csv
 - 649.csv
 - 664.csv
 - 623.csv
 - 667.csv
 - 698.csv
 - 690.csv
 - 64.csv
 - 650.csv
 - 638.csv
 - 645.csv
 - 662.csv
 - 694.csv
 - 683.csv
 - 66.csv
 - 684.csv
 - 634.csv
 - 69.csv
 - 655.csv
 - 666.csv
 - 641.csv
 - 654.csv
 - 630.csv
 - 629.csv
 - 656.csv
 - 689.csv
 - 665.csv
 - 668.csv
 - 663.csv
 - 63.csv
 - 653.csv
 - 680.csv
 - 619.csv
 - 675.csv
 - 647.csv
 - 67.csv
 - 62.csv
 - 618.csv
 - 672.csv
 - 621.csv
 - 661.csv
 - 695.csv
 - 685.csv
 - 614.csv
 - 632.csv
 - 678.csv
 - 681.csv
 - 615.csv
 - 697.csv
 - 677.csv
 - 628.csv
 - 616.csv
 - 636.csv
 - 682.csv
 - 622.csv
 - 617.csv
 - 674.csv
 - 670.csv
 - 687.csv
 - 679.csv
 - 631.csv
 - 65.csv
 - 642.csv
 - 624.csv
 - 644.csv
 - 633.csv
 - 658.csv
 - 671.csv
 - 673.csv
 - 627.csv
 - 691.csv
 - 692.csv
 - 676.csv
 - 639.csv
 - 625.csv
 - 651.csv
 - 620.csv
 - 693.csv
 - 640.csv
 - 660.csv
 - 688.csv
 - 669.csv
 - 646.csv
 - 68.csv
 - 686.csv
 - 659.csv
 - 657.csv
 - 626.csv
 - 635.csv
 - 648.csv
 - 652.csv
 - 712.csv
 - 719.csv
 - 758.csv
 - 772.csv
 - 7.csv
 - 769.csv
 - 761.csv
 - 760.csv
 - 731.csv
 - 704.csv
 - 752.csv
 - 771.csv
 - 77.csv
 - 786.csv
 - 732.csv
 - 729.csv
 - 770.csv
 - 783.csv
 - 767.csv
 - 708.csv
 - 711.csv
 - 785.csv
 - 781.csv
 - 755.csv
 - 724.csv
 - 790.csv
 - 738.csv
 - 722.csv
 - 78.csv
 - 713.csv
 - 733.csv
 - 699.csv
 - 788.csv
 - 71.csv
 - 773.csv
 - 709.csv
 - 74.csv
 - 766.csv
 - 737.csv
 - 742.csv
 - 706.csv
 - 707.csv
 - 73.csv
 - 782.csv
 - 792.csv
 - 756.csv
 - 789.csv
 - 725.csv
 - 730.csv
 - 735.csv
 - 727.csv
 - 703.csv
 - 728.csv
 - 759.csv
 - 787.csv
 - 795.csv
 - 701.csv
 - 734.csv
 - 784.csv
 - 775.csv
 - 743.csv
 - 739.csv
 - 715.csv
 - 745.csv
 - 70.csv
 - 710.csv
 - 780.csv
 - 791.csv
 - 717.csv
 - 75.csv
 - 79.csv
 - 748.csv
 - 744.csv
 - 777.csv
 - 754.csv
 - 764.csv
 - 765.csv
 - 763.csv
 - 751.csv
 - 779.csv
 - 76.csv
 - 716.csv
 - 741.csv
 - 757.csv
 - 720.csv
 - 746.csv
 - 796.csv
 - 753.csv
 - 736.csv
 - 778.csv
 - 749.csv
 - 714.csv
 - 72.csv
 - 774.csv
 - 794.csv
 - 718.csv
 - 750.csv
 - 747.csv
 - 768.csv
 - 762.csv
 - 740.csv
 - 721.csv
 - 793.csv
 - 702.csv
 - 705.csv
 - 723.csv
 - 700.csv
 - 776.csv
 - 726.csv
 - 889.csv
 - 820.csv
 - 845.csv
 - 863.csv
 - 850.csv
 - 852.csv
 - 860.csv
 - 827.csv
 - 849.csv
 - 884.csv
 - 814.csv
 - 839.csv
 - 86.csv
 - 88.csv
 - 876.csv
 - 864.csv
 - 841.csv
 - 853.csv
 - 834.csv
 - 848.csv
 - 855.csv
 - 831.csv
 - 885.csv
 - 821.csv
 - 851.csv
 - 846.csv
 - 859.csv
 - 805.csv
 - 812.csv
 - 872.csv
 - 835.csv
 - 873.csv
 - 813.csv
 - 888.csv
 - 874.csv
 - 804.csv
 - 803.csv
 - 810.csv
 - 883.csv
 - 829.csv
 - 828.csv
 - 890.csv
 - 809.csv
 - 882.csv
 - 816.csv
 - 811.csv
 - 807.csv
 - 836.csv
 - 84.csv
 - 830.csv
 - 861.csv
 - 89.csv
 - 866.csv
 - 85.csv
 - 87.csv
 - 862.csv
 - 797.csv
 - 799.csv
 - 822.csv
 - 842.csv
 - 844.csv
 - 81.csv
 - 887.csv
 - 824.csv
 - 823.csv
 - 806.csv
 - 826.csv
 - 854.csv
 - 808.csv
 - 832.csv
 - 871.csv
 - 847.csv
 - 82.csv
 - 875.csv
 - 868.csv
 - 833.csv
 - 843.csv
 - 83.csv
 - 837.csv
 - 879.csv
 - 817.csv
 - 800.csv
 - 880.csv
 - 840.csv
 - 886.csv
 - 869.csv
 - 856.csv
 - 815.csv
 - 8.csv
 - 877.csv
 - 818.csv
 - 80.csv
 - 867.csv
 - 858.csv
 - 801.csv
 - 857.csv
 - 878.csv
 - 802.csv
 - 870.csv
 - 825.csv
 - 838.csv
 - 865.csv
 - 881.csv
 - 798.csv
 - 819.csv
 - 966.csv
 - 891.csv
 - 957.csv
 - 95.csv
 - 92.csv
 - 985.csv
 - 980.csv
 - 974.csv
 - 959.csv
 - 894.csv
 - 937.csv
 - 956.csv
 - 921.csv
 - 901.csv
 - 899.csv
 - 946.csv
 - 960.csv
 - 919.csv
 - 98.csv
 - 958.csv
 - 94.csv
 - 972.csv
 - 908.csv
 - 963.csv
 - 915.csv
 - 932.csv
 - 979.csv
 - 935.csv
 - 926.csv
 - 96.csv
 - 941.csv
 - 927.csv
 - 920.csv
 - 955.csv
 - 969.csv
 - 971.csv
 - 940.csv
 - 968.csv
 - 91.csv
 - 918.csv
 - 949.csv
 - 893.csv
 - 984.csv
 - 951.csv
 - 897.csv
 - 912.csv
 - 947.csv
 - 929.csv
 - 9.csv
 - 981.csv
 - 964.csv
 - 910.csv
 - 973.csv
 - 93.csv
 - 933.csv
 - 907.csv
 - 978.csv
 - 906.csv
 - 975.csv
 - 895.csv
 - 925.csv
 - 914.csv
 - 945.csv
 - 939.csv
 - 936.csv
 - 905.csv
 - 986.csv
 - 954.csv
 - 913.csv
 - 911.csv
 - 942.csv
 - 928.csv
 - 904.csv
 - 896.csv
 - 962.csv
 - 950.csv
 - 898.csv
 - 976.csv
 - 965.csv
 - 931.csv
 - 952.csv
 - 922.csv
 - 970.csv
 - 900.csv
 - 930.csv
 - 97.csv
 - 909.csv
 - 90.csv
 - 902.csv
 - 924.csv
 - 917.csv
 - 938.csv
 - 943.csv
 - 961.csv
 - 934.csv
 - 983.csv
 - 944.csv
 - 892.csv
 - 967.csv
 - 948.csv
 - 953.csv
 - 916.csv
 - 982.csv
 - 923.csv
 - 903.csv
 - 977.csv
 - 998.csv
 - 994.csv
 - 997.csv
 - 987.csv
 - 992.csv
 - 99.csv
 - 999.csv
 - 988.csv
 - 993.csv
 - 996.csv
 - 995.csv
 - 990.csv
 - 991.csv
 - 989.csv
 - 1078.csv
 - 1036.csv
 - 105.csv
 - 1055.csv
 - 1007.csv
 - 1072.csv
 - 1062.csv
 - 1021.csv
 - 1019.csv
 - 1032.csv
 - 1077.csv
 - 1010.csv
 - 1057.csv
 - 1061.csv
 - 1059.csv
 - 1041.csv
 - 1073.csv
 - 1037.csv
 - 1053.csv
 - 1042.csv
 - 1028.csv
 - 1076.csv
 - 1025.csv
 - 1020.csv
 - 1011.csv
 - 10.csv
 - 1070.csv
 - 106.csv
 - 1075.csv
 - 1079.csv
 - 1063.csv
 - 1060.csv
 - 1044.csv
 - 1065.csv
 - 101.csv
 - 1022.csv
 - 1049.csv
 - 1005.csv
 - 1001.csv
 - 1038.csv
 - 1069.csv
 - 1056.csv
 - 1039.csv
 - 1051.csv
 - 1030.csv
 - 1045.csv
 - 1023.csv
 - 1006.csv
 - 1035.csv
 - 1024.csv
 - 1071.csv
 - 1047.csv
 - 1033.csv
 - 1054.csv
 - 1008.csv
 - 1067.csv
 - 1046.csv
 - 1029.csv
 - 1031.csv
 - 1064.csv
 - 1050.csv
 - 1018.csv
 - 102.csv
 - 1004.csv
 - 108.csv
 - 1026.csv
 - 100.csv
 - 1040.csv
 - 1013.csv
 - 1000.csv
 - 107.csv
 - 1014.csv
 - 1068.csv
 - 1.csv
 - 1058.csv
 - 1052.csv
 - 104.csv
 - 1043.csv
 - 103.csv
 - 1012.csv
 - 1015.csv
 - 1017.csv
 - 1027.csv
 - 1009.csv
 - 1048.csv
 - 1074.csv
 - 1016.csv
 - 1034.csv
 - 1002.csv
 - 1066.csv
 - 1003.csv
 - 1155.csv
 - 1127.csv
 - 1119.csv
 - 1095.csv
 - 1081.csv
 - 1080.csv
 - 1148.csv
 - 1083.csv
 - 113.csv
 - 1099.csv
 - 115.csv
 - 1151.csv
 - 1125.csv
 - 1159.csv
 - 1144.csv
 - 1140.csv
 - 1103.csv
 - 1132.csv
 - 1135.csv
 - 1122.csv
 - 1161.csv
 - 1104.csv
 - 1142.csv
 - 1091.csv
 - 1165.csv
 - 1171.csv
 - 1134.csv
 - 1137.csv
 - 1110.csv
 - 1133.csv
 - 112.csv
 - 1145.csv
 - 1172.csv
 - 1123.csv
 - 1088.csv
 - 1112.csv
 - 1116.csv
 - 109.csv
 - 1109.csv
 - 1092.csv
 - 1121.csv
 - 116.csv
 - 1164.csv
 - 1131.csv
 - 1120.csv
 - 1098.csv
 - 1168.csv
 - 1166.csv
 - 1163.csv
 - 1107.csv
 - 1158.csv
 - 1126.csv
 - 1115.csv
 - 1089.csv
 - 1097.csv
 - 1114.csv
 - 1085.csv
 - 1094.csv
 - 114.csv
 - 1108.csv
 - 1162.csv
 - 1117.csv
 - 1152.csv
 - 1105.csv
 - 1153.csv
 - 1118.csv
 - 11.csv
 - 1096.csv
 - 1149.csv
 - 1111.csv
 - 1106.csv
 - 1130.csv
 - 1139.csv
 - 1169.csv
 - 1113.csv
 - 117.csv
 - 1101.csv
 - 1154.csv
 - 1167.csv
 - 110.csv
 - 1087.csv
 - 1129.csv
 - 1143.csv
 - 1160.csv
 - 1086.csv
 - 1136.csv
 - 111.csv
 - 1141.csv
 - 1138.csv
 - 1093.csv
 - 1124.csv
 - 1128.csv
 - 1090.csv
 - 1147.csv
 - 1150.csv
 - 1082.csv
 - 1084.csv
 - 1100.csv
 - 1170.csv
 - 1102.csv
 - 1157.csv
 - 1156.csv
 - 1146.csv
 - 1227.csv
 - 124.csv
 - 1244.csv
 - 1173.csv
 - 1208.csv
 - 121.csv
 - 123.csv
 - 1199.csv
 - 1232.csv
 - 1213.csv
 - 1238.csv
 - 133.csv
 - 1237.csv
 - 1243.csv
 - 1224.csv
 - 1211.csv
 - 130.csv
 - 1236.csv
 - 1193.csv
 - 1242.csv
 - 1233.csv
 - 1176.csv
 - 128.csv
 - 1212.csv
 - 119.csv
 - 1231.csv
 - 1190.csv
 - 1177.csv
 - 1235.csv
 - 1219.csv
 - 12.csv
 - 136.csv
 - 125.csv
 - 132.csv
 - 1215.csv
 - 142.csv
 - 1204.csv
 - 122.csv
 - 1246.csv
 - 1189.csv
 - 1225.csv
 - 134.csv
 - 126.csv
 - 1187.csv
 - 129.csv
 - 1200.csv
 - 1247.csv
 - 1240.csv
 - 1206.csv
 - 1175.csv
 - 144.csv
 - 1195.csv
 - 1249.csv
 - 145.csv
 - 1226.csv
 - 1184.csv

In [ ]:
bitbrains_files = list(RAW_DIR.iterdir())

print(f"Files found: {len(bitbrains_files)}\n")

for file in bitbrains_files:
    print(
        f"{file.name:<50} "
        f"{file.stat().st_size / (1024**2):.2f} MB"
    )

Files found: 1250

1234.csv                                           0.73 MB
138.csv                                            1.02 MB
1207.csv                                           0.84 MB
1250.csv                                           0.50 MB
1241.csv                                           0.50 MB
1239.csv                                           0.50 MB
1202.csv                                           0.87 MB
139.csv                                            1.03 MB
143.csv                                            1.11 MB
1201.csv                                           0.68 MB
1194.csv                                           0.67 MB
1186.csv                                           0.79 MB
1205.csv                                           0.94 MB
120.csv                                            1.01 MB
1218.csv                                           1.02 MB
1198.csv                                           0.73 MB
118.csv                                            0.99 MB
1178.csv                                           0.79 MB
1182.csv                                           0.78 MB
1188.csv                                           1.09 MB
1220.csv                                           0.97 MB
1174.csv                                           0.79 MB
1230.csv                                           1.13 MB
1222.csv                                           0.97 MB
1181.csv                                           0.79 MB
146.csv                                            1.11 MB
1203.csv                                           0.92 MB
140.csv                                            1.02 MB
1210.csv                                           0.47 MB
13.csv                                             0.71 MB
1180.csv                                           0.79 MB
1197.csv                                           0.81 MB
1217.csv                                           0.78 MB
127.csv                                            1.02 MB
1209.csv                                           0.01 MB
141.csv                                            1.09 MB
1196.csv                                           0.94 MB
131.csv                                            1.12 MB
1192.csv                                           0.77 MB
1216.csv                                           0.73 MB
1248.csv                                           0.50 MB
1223.csv                                           0.40 MB
1229.csv                                           1.12 MB
1221.csv                                           0.97 MB
1191.csv                                           0.76 MB
137.csv                                            1.01 MB
14.csv                                             0.93 MB
1185.csv                                           0.78 MB
1245.csv                                           0.50 MB
1214.csv                                           1.13 MB
1183.csv                                           0.78 MB
1228.csv                                           1.19 MB
135.csv                                            1.09 MB
1179.csv                                           0.92 MB
227.csv                                            0.91 MB
196.csv                                            1.22 MB
219.csv                                            0.95 MB
199.csv                                            1.16 MB
156.csv                                            1.14 MB
237.csv                                            0.91 MB
203.csv                                            1.15 MB
158.csv                                            0.77 MB
224.csv                                            0.91 MB
172.csv                                            1.01 MB
232.csv                                            0.89 MB
19.csv                                             0.93 MB
211.csv                                            1.01 MB
230.csv                                            0.90 MB
168.csv                                            1.32 MB
175.csv                                            0.72 MB
159.csv                                            0.97 MB
162.csv                                            0.11 MB
209.csv                                            0.98 MB
205.csv                                            1.16 MB
214.csv                                            1.15 MB
220.csv                                            0.91 MB
226.csv                                            0.92 MB
216.csv                                            1.16 MB
223.csv                                            0.92 MB
148.csv                                            0.95 MB
15.csv                                             1.19 MB
151.csv                                            0.90 MB
204.csv                                            1.16 MB
234.csv                                            0.89 MB
194.csv                                            1.16 MB
173.csv                                            0.72 MB
152.csv                                            0.72 MB
183.csv                                            1.22 MB
206.csv                                            1.16 MB
20.csv                                             0.51 MB
222.csv                                            0.92 MB
180.csv                                            1.29 MB
201.csv                                            1.15 MB
187.csv                                            1.16 MB
176.csv                                            0.88 MB
169.csv                                            0.98 MB
163.csv                                            0.87 MB
184.csv                                            1.27 MB
160.csv                                            0.96 MB
164.csv                                            0.97 MB
190.csv                                            1.17 MB
186.csv                                            1.21 MB
149.csv                                            1.14 MB
21.csv                                             0.85 MB
212.csv                                            1.16 MB
221.csv                                            0.90 MB
179.csv                                            1.28 MB
195.csv                                            1.22 MB
171.csv                                            0.89 MB
16.csv                                             0.93 MB
166.csv                                            0.90 MB
197.csv                                            1.16 MB
155.csv                                            0.92 MB
236.csv                                            0.90 MB
22.csv                                             1.12 MB
185.csv                                            1.19 MB
202.csv                                            1.16 MB
189.csv                                            1.16 MB
210.csv                                            1.27 MB
235.csv                                            0.90 MB
147.csv                                            1.11 MB
233.csv                                            0.90 MB
157.csv                                            0.93 MB
217.csv                                            1.16 MB
154.csv                                            0.89 MB
193.csv                                            1.17 MB
182.csv                                            0.75 MB
177.csv                                            0.80 MB
23.csv                                             1.09 MB
174.csv                                            0.87 MB
161.csv                                            0.07 MB
208.csv                                            1.16 MB
150.csv                                            1.06 MB
228.csv                                            0.91 MB
181.csv                                            1.02 MB
2.csv                                              0.93 MB
167.csv                                            0.95 MB
188.csv                                            1.16 MB
215.csv                                            1.16 MB
191.csv                                            1.16 MB
153.csv                                            0.89 MB
18.csv                                             0.93 MB
238.csv                                            0.90 MB
198.csv                                            1.16 MB
213.csv                                            1.01 MB
229.csv                                            0.90 MB
225.csv                                            0.90 MB
200.csv                                            1.18 MB
170.csv                                            0.64 MB
231.csv                                            0.90 MB
192.csv                                            1.22 MB
17.csv                                             0.96 MB
165.csv                                            1.03 MB
218.csv                                            1.07 MB
178.csv                                            0.82 MB
207.csv                                            1.15 MB
251.csv                                            1.07 MB
283.csv                                            1.05 MB
305.csv                                            0.95 MB
329.csv                                            1.19 MB
284.csv                                            1.06 MB
266.csv                                            1.06 MB
269.csv                                            1.07 MB
293.csv                                            0.99 MB
294.csv                                            1.02 MB
272.csv                                            1.07 MB
303.csv                                            0.22 MB
313.csv                                            0.52 MB
319.csv                                            1.14 MB
256.csv                                            1.07 MB
267.csv                                            1.07 MB
290.csv                                            1.03 MB
252.csv                                            1.07 MB
257.csv                                            1.07 MB
321.csv                                            1.25 MB
315.csv                                            1.12 MB
323.csv                                            1.14 MB
281.csv                                            1.05 MB
287.csv                                            1.04 MB
3.csv                                              1.11 MB
248.csv                                            1.07 MB
322.csv                                            1.25 MB
26.csv                                             0.97 MB
277.csv                                            1.04 MB
260.csv                                            1.05 MB
307.csv                                            0.94 MB
292.csv                                            0.99 MB
330.csv                                            1.11 MB
326.csv                                            1.16 MB
320.csv                                            1.00 MB
295.csv                                            0.94 MB
29.csv                                             0.81 MB
325.csv                                            1.11 MB
286.csv                                            1.04 MB
278.csv                                            1.06 MB
270.csv                                            1.07 MB
32.csv                                             1.00 MB
304.csv                                            0.22 MB
33.csv                                             1.03 MB
240.csv                                            1.08 MB
316.csv                                            0.00 MB
276.csv                                            1.06 MB
288.csv                                            1.06 MB
328.csv                                            1.06 MB
27.csv                                             0.95 MB
282.csv                                            1.04 MB
255.csv                                            1.06 MB
241.csv                                            1.06 MB
259.csv                                            1.07 MB
254.csv                                            1.10 MB
291.csv                                            1.05 MB
324.csv                                            0.98 MB
243.csv                                            1.06 MB
327.csv                                            1.06 MB
279.csv                                            1.06 MB
306.csv                                            0.93 MB
249.csv                                            1.06 MB
274.csv                                            1.05 MB
250.csv                                            1.08 MB
268.csv                                            1.07 MB
289.csv                                            1.06 MB
317.csv                                            1.06 MB
264.csv                                            1.06 MB
239.csv                                            1.08 MB
311.csv                                            0.95 MB
302.csv                                            1.07 MB
271.csv                                            1.06 MB
30.csv                                             0.71 MB
258.csv                                            1.07 MB
300.csv                                            1.03 MB
25.csv                                             1.06 MB
28.csv                                             0.87 MB
263.csv                                            1.05 MB
275.csv                                            1.05 MB
265.csv                                            1.05 MB
262.csv                                            1.06 MB
285.csv                                            1.06 MB
331.csv                                            0.73 MB
309.csv                                            0.22 MB
31.csv                                             1.07 MB
297.csv                                            1.23 MB
242.csv                                            1.10 MB
280.csv                                            1.05 MB
299.csv                                            1.00 MB
301.csv                                            1.03 MB
244.csv                                            1.06 MB
308.csv                                            0.23 MB
246.csv                                            1.08 MB
261.csv                                            1.07 MB
310.csv                                            0.22 MB
24.csv                                             1.00 MB
247.csv                                            1.07 MB
296.csv                                            1.08 MB
314.csv                                            0.02 MB
312.csv                                            0.00 MB
253.csv                                            1.06 MB
318.csv                                            0.70 MB
298.csv                                            1.01 MB
273.csv                                            1.05 MB
245.csv                                            1.06 MB
346.csv                                            1.15 MB
376.csv                                            0.98 MB
373.csv                                            0.99 MB
393.csv                                            1.05 MB
359.csv                                            1.42 MB
424.csv                                            0.99 MB
401.csv                                            1.04 MB
418.csv                                            1.04 MB
360.csv                                            1.18 MB
405.csv                                            1.04 MB
350.csv                                            1.16 MB
385.csv                                            0.97 MB
404.csv                                            1.06 MB
342.csv                                            0.64 MB
365.csv                                            0.72 MB
410.csv                                            1.04 MB
332.csv                                            1.17 MB
379.csv                                            0.97 MB
400.csv                                            1.04 MB
341.csv                                            1.03 MB
356.csv                                            1.09 MB
394.csv                                            1.03 MB
416.csv                                            1.07 MB
333.csv                                            0.76 MB
415.csv                                            1.06 MB
336.csv                                            0.41 MB
362.csv                                            0.87 MB
352.csv                                            1.19 MB
374.csv                                            0.96 MB
392.csv                                            1.06 MB
389.csv                                            1.08 MB
390.csv                                            0.65 MB
395.csv                                            1.04 MB
334.csv                                            0.97 MB
414.csv                                            1.06 MB
428.csv                                            0.99 MB
339.csv                                            1.14 MB
357.csv                                            1.29 MB
42.csv                                             1.00 MB
347.csv                                            0.82 MB
396.csv                                            1.05 MB
351.csv                                            1.08 MB
406.csv                                            1.06 MB
422.csv                                            1.03 MB
39.csv                                             0.69 MB
408.csv                                            1.05 MB
340.csv                                            1.13 MB
419.csv                                            1.06 MB
343.csv                                            1.15 MB
368.csv                                            1.01 MB
398.csv                                            1.05 MB
348.csv                                            1.18 MB
384.csv                                            1.12 MB
403.csv                                            1.04 MB
420.csv                                            1.05 MB
426.csv                                            0.98 MB
391.csv                                            1.05 MB
377.csv                                            0.98 MB
37.csv                                             0.80 MB
417.csv                                            1.07 MB
386.csv                                            0.99 MB
382.csv                                            0.98 MB
354.csv                                            0.97 MB
388.csv                                            1.22 MB
366.csv                                            1.11 MB
399.csv                                            1.03 MB
36.csv                                             0.85 MB
380.csv                                            0.98 MB
35.csv                                             0.86 MB
349.csv                                            1.14 MB
367.csv                                            1.12 MB
383.csv                                            0.98 MB
425.csv                                            1.02 MB
372.csv                                            1.00 MB
413.csv                                            1.04 MB
427.csv                                            1.01 MB
338.csv                                            0.70 MB
353.csv                                            0.64 MB

In [ ]:
bitbrains_files = list(RAW_DIR.iterdir())

print(f"Files found: {len(bitbrains_files)}\n")

for i, file in enumerate(bitbrains_files, start=1):
    size_mb = file.stat().st_size / (1024 ** 2)
    print(f"{i}. {file.name} — {size_mb:.2f} MB")

Files found: 1250

1. 1234.csv — 0.73 MB
2. 138.csv — 1.02 MB
3. 1207.csv — 0.84 MB
4. 1250.csv — 0.50 MB
5. 1241.csv — 0.50 MB
6. 1239.csv — 0.50 MB
7. 1202.csv — 0.87 MB
8. 139.csv — 1.03 MB
9. 143.csv — 1.11 MB
10. 1201.csv — 0.68 MB
11. 1194.csv — 0.67 MB
12. 1186.csv — 0.79 MB
13. 1205.csv — 0.94 MB
14. 120.csv — 1.01 MB
15. 1218.csv — 1.02 MB
16. 1198.csv — 0.73 MB
17. 118.csv — 0.99 MB
18. 1178.csv — 0.79 MB
19. 1182.csv — 0.78 MB
20. 1188.csv — 1.09 MB
21. 1220.csv — 0.97 MB
22. 1174.csv — 0.79 MB
23. 1230.csv — 1.13 MB
24. 1222.csv — 0.97 MB
25. 1181.csv — 0.79 MB
26. 146.csv — 1.11 MB
27. 1203.csv — 0.92 MB
28. 140.csv — 1.02 MB
29. 1210.csv — 0.47 MB
30. 13.csv — 0.71 MB
31. 1180.csv — 0.79 MB
32. 1197.csv — 0.81 MB
33. 1217.csv — 0.78 MB
34. 127.csv — 1.02 MB
35. 1209.csv — 0.01 MB
36. 141.csv — 1.09 MB
37. 1196.csv — 0.94 MB
38. 131.csv — 1.12 MB
39. 1192.csv — 0.77 MB
40. 1216.csv — 0.73 MB
41. 1248.csv — 0.50 MB
42. 1223.csv — 0.40 MB
43. 1229.csv — 1.12 MB
44. 1221.csv — 0.97 MB
45. 1191.csv — 0.76 MB
46. 137.csv — 1.01 MB
47. 14.csv — 0.93 MB
48. 1185.csv — 0.78 MB
49. 1245.csv — 0.50 MB
50. 1214.csv — 1.13 MB
51. 1183.csv — 0.78 MB
52. 1228.csv — 1.19 MB
53. 135.csv — 1.09 MB
54. 1179.csv — 0.92 MB
55. 227.csv — 0.91 MB
56. 196.csv — 1.22 MB
57. 219.csv — 0.95 MB
58. 199.csv — 1.16 MB
59. 156.csv — 1.14 MB
60. 237.csv — 0.91 MB
61. 203.csv — 1.15 MB
62. 158.csv — 0.77 MB
63. 224.csv — 0.91 MB
64. 172.csv — 1.01 MB
65. 232.csv — 0.89 MB
66. 19.csv — 0.93 MB
67. 211.csv — 1.01 MB
68. 230.csv — 0.90 MB
69. 168.csv — 1.32 MB
70. 175.csv — 0.72 MB
71. 159.csv — 0.97 MB
72. 162.csv — 0.11 MB
73. 209.csv — 0.98 MB
74. 205.csv — 1.16 MB
75. 214.csv — 1.15 MB
76. 220.csv — 0.91 MB
77. 226.csv — 0.92 MB
78. 216.csv — 1.16 MB
79. 223.csv — 0.92 MB
80. 148.csv — 0.95 MB
81. 15.csv — 1.19 MB
82. 151.csv — 0.90 MB
83. 204.csv — 1.16 MB
84. 234.csv — 0.89 MB
85. 194.csv — 1.16 MB
86. 173.csv — 0.72 MB
87. 152.csv — 0.72 MB
88. 183.csv — 1.22 MB
89. 206.csv — 1.16 MB
90. 20.csv — 0.51 MB
91. 222.csv — 0.92 MB
92. 180.csv — 1.29 MB
93. 201.csv — 1.15 MB
94. 187.csv — 1.16 MB
95. 176.csv — 0.88 MB
96. 169.csv — 0.98 MB
97. 163.csv — 0.87 MB
98. 184.csv — 1.27 MB
99. 160.csv — 0.96 MB
100. 164.csv — 0.97 MB
101. 190.csv — 1.17 MB
102. 186.csv — 1.21 MB
103. 149.csv — 1.14 MB
104. 21.csv — 0.85 MB
105. 212.csv — 1.16 MB
106. 221.csv — 0.90 MB
107. 179.csv — 1.28 MB
108. 195.csv — 1.22 MB
109. 171.csv — 0.89 MB
110. 16.csv — 0.93 MB
111. 166.csv — 0.90 MB
112. 197.csv — 1.16 MB
113. 155.csv — 0.92 MB
114. 236.csv — 0.90 MB
115. 22.csv — 1.12 MB
116. 185.csv — 1.19 MB
117. 202.csv — 1.16 MB
118. 189.csv — 1.16 MB
119. 210.csv — 1.27 MB
120. 235.csv — 0.90 MB
121. 147.csv — 1.11 MB
122. 233.csv — 0.90 MB
123. 157.csv — 0.93 MB
124. 217.csv — 1.16 MB
125. 154.csv — 0.89 MB
126. 193.csv — 1.17 MB
127. 182.csv — 0.75 MB
128. 177.csv — 0.80 MB
129. 23.csv — 1.09 MB
130. 174.csv — 0.87 MB
131. 161.csv — 0.07 MB
132. 208.csv — 1.16 MB
133. 150.csv — 1.06 MB
134. 228.csv — 0.91 MB
135. 181.csv — 1.02 MB
136. 2.csv — 0.93 MB
137. 167.csv — 0.95 MB
138. 188.csv — 1.16 MB
139. 215.csv — 1.16 MB
140. 191.csv — 1.16 MB
141. 153.csv — 0.89 MB
142. 18.csv — 0.93 MB
143. 238.csv — 0.90 MB
144. 198.csv — 1.16 MB
145. 213.csv — 1.01 MB
146. 229.csv — 0.90 MB
147. 225.csv — 0.90 MB
148. 200.csv — 1.18 MB
149. 170.csv — 0.64 MB
150. 231.csv — 0.90 MB
151. 192.csv — 1.22 MB
152. 17.csv — 0.96 MB
153. 165.csv — 1.03 MB
154. 218.csv — 1.07 MB
155. 178.csv — 0.82 MB
156. 207.csv — 1.15 MB
157. 251.csv — 1.07 MB
158. 283.csv — 1.05 MB
159. 305.csv — 0.95 MB
160. 329.csv — 1.19 MB
161. 284.csv — 1.06 MB
162. 266.csv — 1.06 MB
163. 269.csv — 1.07 MB
164. 293.csv — 0.99 MB
165. 294.csv — 1.02 MB
166. 272.csv — 1.07 MB
167. 303.csv — 0.22 MB
168. 313.csv — 0.52 MB
169. 319.csv — 1.14 MB
170. 256.csv — 1.07 MB
171. 267.csv — 1.07 MB
172. 290.csv — 1.03 MB
173. 252.csv — 1.07 MB
174. 257.csv — 1.07 MB
175. 321.csv — 1.25 MB
176. 315.csv — 1.12 MB
177. 323.csv — 1.14 MB
178. 281.csv — 1.05 MB
179. 287.csv — 1.04 MB
180. 3.csv — 1.11 MB
181. 248.csv — 1.07 MB
182. 322.csv — 1.25 MB
183. 26.csv — 0.97 MB
184. 277.csv — 1.04 MB
185. 260.csv — 1.05 MB
186. 307.csv — 0.94 MB
187. 292.csv — 0.99 MB
188. 330.csv — 1.11 MB
189. 326.csv — 1.16 MB
190. 320.csv — 1.00 MB
191. 295.csv — 0.94 MB
192. 29.csv — 0.81 MB
193. 325.csv — 1.11 MB
194. 286.csv — 1.04 MB
195. 278.csv — 1.06 MB
196. 270.csv — 1.07 MB
197. 32.csv — 1.00 MB
198. 304.csv — 0.22 MB
199. 33.csv — 1.03 MB
200. 240.csv — 1.08 MB
201. 316.csv — 0.00 MB
202. 276.csv — 1.06 MB
203. 288.csv — 1.06 MB
204. 328.csv — 1.06 MB
205. 27.csv — 0.95 MB
206. 282.csv — 1.04 MB
207. 255.csv — 1.06 MB
208. 241.csv — 1.06 MB
209. 259.csv — 1.07 MB
210. 254.csv — 1.10 MB
211. 291.csv — 1.05 MB
212. 324.csv — 0.98 MB
213. 243.csv — 1.06 MB
214. 327.csv — 1.06 MB
215. 279.csv — 1.06 MB
216. 306.csv — 0.93 MB
217. 249.csv — 1.06 MB
218. 274.csv — 1.05 MB
219. 250.csv — 1.08 MB
220. 268.csv — 1.07 MB
221. 289.csv — 1.06 MB
222. 317.csv — 1.06 MB
223. 264.csv — 1.06 MB
224. 239.csv — 1.08 MB
225. 311.csv — 0.95 MB
226. 302.csv — 1.07 MB
227. 271.csv — 1.06 MB
228. 30.csv — 0.71 MB
229. 258.csv — 1.07 MB
230. 300.csv — 1.03 MB
231. 25.csv — 1.06 MB
232. 28.csv — 0.87 MB
233. 263.csv — 1.05 MB
234. 275.csv — 1.05 MB
235. 265.csv — 1.05 MB
236. 262.csv — 1.06 MB
237. 285.csv — 1.06 MB
238. 331.csv — 0.73 MB
239. 309.csv — 0.22 MB
240. 31.csv — 1.07 MB
241. 297.csv — 1.23 MB
242. 242.csv — 1.10 MB
243. 280.csv — 1.05 MB
244. 299.csv — 1.00 MB
245. 301.csv — 1.03 MB
246. 244.csv — 1.06 MB
247. 308.csv — 0.23 MB
248. 246.csv — 1.08 MB
249. 261.csv — 1.07 MB
250. 310.csv — 0.22 MB
251. 24.csv — 1.00 MB
252. 247.csv — 1.07 MB
253. 296.csv — 1.08 MB
254. 314.csv — 0.02 MB
255. 312.csv — 0.00 MB
256. 253.csv — 1.06 MB
257. 318.csv — 0.70 MB
258. 298.csv — 1.01 MB
259. 273.csv — 1.05 MB
260. 245.csv — 1.06 MB
261. 346.csv — 1.15 MB
262. 376.csv — 0.98 MB
263. 373.csv — 0.99 MB
264. 393.csv — 1.05 MB
265. 359.csv — 1.42 MB
266. 424.csv — 0.99 MB
267. 401.csv — 1.04 MB
268. 418.csv — 1.04 MB
269. 360.csv — 1.18 MB
270. 405.csv — 1.04 MB
271. 350.csv — 1.16 MB
272. 385.csv — 0.97 MB
273. 404.csv — 1.06 MB
274. 342.csv — 0.64 MB
275. 365.csv — 0.72 MB
276. 410.csv — 1.04 MB
277. 332.csv — 1.17 MB
278. 379.csv — 0.97 MB
279. 400.csv — 1.04 MB
280. 341.csv — 1.03 MB
281. 356.csv — 1.09 MB
282. 394.csv — 1.03 MB
283. 416.csv — 1.07 MB
284. 333.csv — 0.76 MB
285. 415.csv — 1.06 MB
286. 336.csv — 0.41 MB
287. 362.csv — 0.87 MB
288. 352.csv — 1.19 MB
289. 374.csv — 0.96 MB
290. 392.csv — 1.06 MB
291. 389.csv — 1.08 MB
292. 390.csv — 0.65 MB
293. 395.csv — 1.04 MB
294. 334.csv — 0.97 MB
295. 414.csv — 1.06 MB
296. 428.csv — 0.99 MB
297. 339.csv — 1.14 MB
298. 357.csv — 1.29 MB
299. 42.csv — 1.00 MB
300. 347.csv — 0.82 MB
301. 396.csv — 1.05 MB
302. 351.csv — 1.08 MB
303. 406.csv — 1.06 MB
304. 422.csv — 1.03 MB
305. 39.csv — 0.69 MB
306. 408.csv — 1.05 MB
307. 340.csv — 1.13 MB
308. 419.csv — 1.06 MB
309. 343.csv — 1.15 MB
310. 368.csv — 1.01 MB
311. 398.csv — 1.05 MB
312. 348.csv — 1.18 MB
313. 384.csv — 1.12 MB
314. 403.csv — 1.04 MB
315. 420.csv — 1.05 MB
316. 426.csv — 0.98 MB
317. 391.csv — 1.05 MB
318. 377.csv — 0.98 MB
319. 37.csv — 0.80 MB
320. 417.csv — 1.07 MB
321. 386.csv — 0.99 MB
322. 382.csv — 0.98 MB
323. 354.csv — 0.97 MB
324. 388.csv — 1.22 MB
325. 366.csv — 1.11 MB
326. 399.csv — 1.03 MB
327. 36.csv — 0.85 MB
328. 380.csv — 0.98 MB
329. 35.csv — 0.86 MB
330. 349.csv — 1.14 MB
331. 367.csv — 1.12 MB
332. 383.csv — 0.98 MB
333. 425.csv — 1.02 MB
334. 372.csv — 1.00 MB
335. 413.csv — 1.04 MB
336. 427.csv — 1.01 MB
337. 338.csv — 0.70 MB
338. 353.csv — 0.64 MB
339. 375.csv — 0.98 MB
340. 344.csv — 1.16 MB
341. 41.csv — 0.34 MB
342. 34.csv — 0.97 MB
343. 409.csv — 1.04 MB
344. 345.csv — 1.02 MB
345. 378.csv — 0.98 MB
346. 402.csv — 1.04 MB
347. 355.csv — 1.40 MB
348. 411.csv — 1.06 MB
349. 364.csv — 1.21 MB
350. 40.csv — 1.02 MB
351. 38.csv — 0.83 MB
352. 381.csv — 0.88 MB
353. 412.csv — 1.02 MB
354. 361.csv — 1.04 MB
355. 4.csv — 0.97 MB
356. 335.csv — 0.98 MB
357. 337.csv — 1.04 MB
358. 363.csv — 0.85 MB
359. 358.csv — 0.95 MB
360. 397.csv — 1.06 MB
361. 407.csv — 1.05 MB
362. 370.csv — 1.08 MB
363. 387.csv — 1.23 MB
364. 371.csv — 1.08 MB
365. 421.csv — 1.07 MB
366. 369.csv — 1.12 MB
367. 423.csv — 1.02 MB
368. 502.csv — 1.02 MB
369. 444.csv — 0.99 MB
370. 455.csv — 1.04 MB
371. 508.csv — 1.02 MB
372. 51.csv — 0.96 MB
373. 456.csv — 1.03 MB
374. 49.csv — 0.90 MB
375. 488.csv — 1.01 MB
376. 494.csv — 1.00 MB
377. 441.csv — 0.99 MB
378. 430.csv — 1.02 MB
379. 450.csv — 0.99 MB
380. 435.csv — 1.00 MB
381. 462.csv — 1.03 MB
382. 517.csv — 0.99 MB
383. 45.csv — 1.20 MB
384. 511.csv — 1.01 MB
385. 43.csv — 1.13 MB
386. 498.csv — 1.00 MB
387. 495.csv — 1.00 MB
388. 477.csv — 1.02 MB
389. 439.csv — 0.98 MB
390. 445.csv — 0.99 MB
391. 519.csv — 1.01 MB
392. 453.csv — 1.01 MB
393. 431.csv — 1.01 MB
394. 5.csv — 0.93 MB
395. 468.csv — 1.01 MB
396. 442.csv — 0.98 MB
397. 492.csv — 1.01 MB
398. 472.csv — 1.02 MB
399. 487.csv — 1.00 MB
400. 475.csv — 1.01 MB
401. 50.csv — 1.02 MB
402. 471.csv — 1.00 MB
403. 473.csv — 1.01 MB
404. 516.csv — 0.98 MB
405. 449.csv — 0.99 MB
406. 432.csv — 1.01 MB
407. 434.csv — 1.02 MB
408. 479.csv — 1.00 MB
409. 482.csv — 1.00 MB
410. 501.csv — 1.00 MB
411. 504.csv — 1.00 MB
412. 440.csv — 0.99 MB
413. 463.csv — 1.01 MB
414. 484.csv — 0.98 MB
415. 452.csv — 1.00 MB
416. 489.csv — 1.00 MB
417. 438.csv — 1.00 MB
418. 448.csv — 0.98 MB
419. 490.csv — 0.99 MB
420. 521.csv — 1.02 MB
421. 436.csv — 1.01 MB
422. 522.csv — 1.01 MB
423. 507.csv — 1.00 MB
424. 459.csv — 1.02 MB
425. 478.csv — 1.01 MB
426. 500.csv — 1.01 MB
427. 503.csv — 1.01 MB
428. 513.csv — 1.00 MB
429. 464.csv — 1.01 MB
430. 493.csv — 0.99 MB
431. 465.csv — 1.03 MB
432. 518.csv — 1.01 MB
433. 52.csv — 0.83 MB
434. 443.csv — 1.01 MB
435. 44.csv — 0.91 MB
436. 523.csv — 1.01 MB
437. 480.csv — 1.00 MB
438. 447.csv — 1.01 MB
439. 497.csv — 0.99 MB
440. 499.csv — 0.99 MB
441. 474.csv — 1.01 MB
442. 46.csv — 0.96 MB
443. 446.csv — 1.01 MB
444. 514.csv — 1.00 MB
445. 437.csv — 1.00 MB
446. 457.csv — 1.01 MB
447. 486.csv — 1.00 MB
448. 509.csv — 1.01 MB
449. 461.csv — 1.03 MB
450. 496.csv — 1.01 MB
451. 512.csv — 1.00 MB
452. 470.csv — 1.03 MB
453. 491.csv — 1.02 MB
454. 467.csv — 1.02 MB
455. 458.csv — 1.01 MB
456. 47.csv — 1.11 MB
457. 505.csv — 1.01 MB
458. 483.csv — 1.02 MB
459. 481.csv — 1.01 MB
460. 460.csv — 1.03 MB
461. 469.csv — 1.00 MB
462. 520.csv — 1.01 MB
463. 515.csv — 1.02 MB
464. 433.csv — 1.02 MB
465. 506.csv — 1.01 MB
466. 466.csv — 0.99 MB
467. 454.csv — 1.03 MB
468. 476.csv — 1.01 MB
469. 510.csv — 1.02 MB
470. 429.csv — 0.99 MB
471. 485.csv — 1.02 MB
472. 451.csv — 1.00 MB
473. 48.csv — 0.71 MB
474. 566.csv — 0.68 MB
475. 537.csv — 1.16 MB
476. 524.csv — 0.99 MB
477. 564.csv — 0.67 MB
478. 578.csv — 0.63 MB
479. 605.csv — 0.62 MB
480. 529.csv — 0.95 MB
481. 601.csv — 1.08 MB
482. 569.csv — 0.66 MB
483. 599.csv — 0.95 MB
484. 547.csv — 0.93 MB
485. 545.csv — 0.99 MB
486. 574.csv — 1.04 MB
487. 593.csv — 0.99 MB
488. 580.csv — 0.99 MB
489. 55.csv — 1.06 MB
490. 609.csv — 0.92 MB
491. 548.csv — 0.89 MB
492. 612.csv — 0.91 MB
493. 586.csv — 0.92 MB
494. 600.csv — 1.11 MB
495. 572.csv — 0.67 MB
496. 562.csv — 1.04 MB
497. 607.csv — 1.01 MB
498. 536.csv — 0.49 MB
499. 571.csv — 0.66 MB
500. 582.csv — 1.08 MB
501. 581.csv — 0.78 MB
502. 533.csv — 0.69 MB
503. 54.csv — 1.12 MB
504. 613.csv — 0.91 MB
505. 543.csv — 1.41 MB
506. 53.csv — 0.51 MB
507. 544.csv — 0.70 MB
508. 527.csv — 1.10 MB
509. 570.csv — 0.66 MB
510. 549.csv — 0.84 MB
511. 552.csv — 0.04 MB
512. 591.csv — 0.86 MB
513. 575.csv — 0.76 MB
514. 584.csv — 1.01 MB
515. 583.csv — 1.02 MB
516. 556.csv — 0.88 MB
517. 576.csv — 0.00 MB
518. 58.csv — 1.13 MB
519. 59.csv — 0.00 MB
520. 558.csv — 0.72 MB
521. 557.csv — 0.19 MB
522. 539.csv — 0.99 MB
523. 542.csv — 1.31 MB
524. 534.csv — 1.04 MB
525. 567.csv — 0.67 MB
526. 528.csv — 0.99 MB
527. 579.csv — 1.03 MB
528. 541.csv — 1.14 MB
529. 563.csv — 0.72 MB
530. 540.csv — 1.05 MB
531. 551.csv — 1.08 MB
532. 585.csv — 1.01 MB
533. 592.csv — 1.10 MB
534. 538.csv — 0.81 MB
535. 588.csv — 0.93 MB
536. 604.csv — 1.01 MB
537. 531.csv — 1.07 MB
538. 553.csv — 0.06 MB
539. 530.csv — 0.97 MB
540. 611.csv — 0.91 MB
541. 554.csv — 0.79 MB
542. 596.csv — 1.01 MB
543. 606.csv — 0.90 MB
544. 590.csv — 0.94 MB
545. 6.csv — 0.93 MB
546. 598.csv — 0.94 MB
547. 589.csv — 1.10 MB
548. 535.csv — 0.83 MB
549. 560.csv — 0.76 MB
550. 610.csv — 0.91 MB
551. 61.csv — 1.76 MB
552. 550.csv — 0.88 MB
553. 568.csv — 0.68 MB
554. 561.csv — 1.33 MB
555. 587.csv — 1.04 MB
556. 532.csv — 1.07 MB
557. 603.csv — 0.95 MB
558. 56.csv — 1.17 MB
559. 602.csv — 1.12 MB
560. 577.csv — 0.69 MB
561. 573.csv — 0.66 MB
562. 526.csv — 0.98 MB
563. 60.csv — 1.18 MB
564. 595.csv — 1.04 MB
565. 546.csv — 1.08 MB
566. 559.csv — 0.85 MB
567. 597.csv — 1.01 MB
568. 594.csv — 0.99 MB
569. 565.csv — 0.69 MB
570. 608.csv — 1.43 MB
571. 57.csv — 1.18 MB
572. 555.csv — 1.09 MB
573. 525.csv — 1.02 MB
574. 643.csv — 1.24 MB
575. 696.csv — 0.28 MB
576. 637.csv — 1.29 MB
577. 649.csv — 1.23 MB
578. 664.csv — 1.02 MB
579. 623.csv — 1.23 MB
580. 667.csv — 1.37 MB
581. 698.csv — 1.00 MB
582. 690.csv — 1.10 MB
583. 64.csv — 1.34 MB
584. 650.csv — 1.23 MB
585. 638.csv — 1.24 MB
586. 645.csv — 1.23 MB
587. 662.csv — 1.03 MB
588. 694.csv — 0.31 MB
589. 683.csv — 0.94 MB
590. 66.csv — 1.07 MB
591. 684.csv — 0.87 MB
592. 634.csv — 1.23 MB
593. 69.csv — 1.12 MB
594. 655.csv — 1.23 MB
595. 666.csv — 1.02 MB
596. 641.csv — 1.24 MB
597. 654.csv — 1.42 MB
598. 630.csv — 1.22 MB
599. 629.csv — 1.23 MB
600. 656.csv — 1.13 MB
601. 689.csv — 1.16 MB
602. 665.csv — 1.01 MB
603. 668.csv — 0.14 MB
604. 663.csv — 1.02 MB
605. 63.csv — 1.10 MB
606. 653.csv — 1.23 MB
607. 680.csv — 1.08 MB
608. 619.csv — 0.96 MB
609. 675.csv — 1.11 MB
610. 647.csv — 1.23 MB
611. 67.csv — 1.09 MB
612. 62.csv — 1.12 MB
613. 618.csv — 0.96 MB
614. 672.csv — 0.34 MB
615. 621.csv — 0.96 MB
616. 661.csv — 1.03 MB
617. 695.csv — 0.31 MB
618. 685.csv — 0.97 MB
619. 614.csv — 1.24 MB
620. 632.csv — 1.23 MB
621. 678.csv — 1.04 MB
622. 681.csv — 1.11 MB
623. 615.csv — 1.44 MB
624. 697.csv — 1.05 MB
625. 677.csv — 1.11 MB
626. 628.csv — 1.23 MB
627. 616.csv — 1.25 MB
628. 636.csv — 1.25 MB
629. 682.csv — 1.00 MB
630. 622.csv — 0.97 MB
631. 617.csv — 0.97 MB
632. 674.csv — 0.00 MB
633. 670.csv — 1.22 MB
634. 687.csv — 0.36 MB
635. 679.csv — 1.01 MB
636. 631.csv — 1.24 MB
637. 65.csv — 1.19 MB
638. 642.csv — 1.24 MB
639. 624.csv — 1.24 MB
640. 644.csv — 1.24 MB
641. 633.csv — 1.23 MB
642. 658.csv — 1.03 MB
643. 671.csv — 0.88 MB
644. 673.csv — 0.09 MB
645. 627.csv — 1.23 MB
646. 691.csv — 1.01 MB
647. 692.csv — 1.11 MB
648. 676.csv — 1.10 MB
649. 639.csv — 1.24 MB
650. 625.csv — 1.23 MB
651. 651.csv — 1.22 MB
652. 620.csv — 0.97 MB
653. 693.csv — 1.07 MB
654. 640.csv — 1.23 MB
655. 660.csv — 1.04 MB
656. 688.csv — 1.06 MB
657. 669.csv — 0.72 MB
658. 646.csv — 1.25 MB
659. 68.csv — 1.34 MB
660. 686.csv — 1.06 MB
661. 659.csv — 1.03 MB
662. 657.csv — 1.08 MB
663. 626.csv — 1.23 MB
664. 635.csv — 1.23 MB
665. 648.csv — 1.25 MB
666. 652.csv — 1.23 MB
667. 712.csv — 0.92 MB
668. 719.csv — 0.93 MB
669. 758.csv — 1.01 MB
670. 772.csv — 1.07 MB
671. 7.csv — 0.93 MB
672. 769.csv — 0.97 MB
673. 761.csv — 0.88 MB
674. 760.csv — 0.98 MB
675. 731.csv — 1.26 MB
676. 704.csv — 1.02 MB
677. 752.csv — 0.50 MB
678. 771.csv — 0.64 MB
679. 77.csv — 1.14 MB
680. 786.csv — 0.18 MB
681. 732.csv — 1.09 MB
682. 729.csv — 0.88 MB
683. 770.csv — 0.76 MB
684. 783.csv — 1.12 MB
685. 767.csv — 1.07 MB
686. 708.csv — 0.91 MB
687. 711.csv — 0.92 MB
688. 785.csv — 0.19 MB
689. 781.csv — 0.20 MB
690. 755.csv — 0.79 MB
691. 724.csv — 0.63 MB
692. 790.csv — 0.32 MB
693. 738.csv — 1.04 MB
694. 722.csv — 1.02 MB
695. 78.csv — 1.06 MB
696. 713.csv — 0.94 MB
697. 733.csv — 0.94 MB
698. 699.csv — 1.03 MB
699. 788.csv — 0.18 MB
700. 71.csv — 1.09 MB
701. 773.csv — 0.85 MB
702. 709.csv — 0.91 MB
703. 74.csv — 1.16 MB
704. 766.csv — 1.12 MB
705. 737.csv — 0.93 MB
706. 742.csv — 1.10 MB
707. 706.csv — 0.98 MB
708. 707.csv — 0.74 MB
709. 73.csv — 1.52 MB
710. 782.csv — 1.01 MB
711. 792.csv — 1.07 MB
712. 756.csv — 0.00 MB
713. 789.csv — 0.98 MB
714. 725.csv — 1.00 MB
715. 730.csv — 0.89 MB
716. 735.csv — 1.02 MB
717. 727.csv — 0.63 MB
718. 703.csv — 1.00 MB
719. 728.csv — 1.11 MB
720. 759.csv — 0.89 MB
721. 787.csv — 0.17 MB
722. 795.csv — 0.99 MB
723. 701.csv — 1.02 MB
724. 734.csv — 1.03 MB
725. 784.csv — 0.19 MB
726. 775.csv — 1.10 MB
727. 743.csv — 1.03 MB
728. 739.csv — 1.08 MB
729. 715.csv — 0.90 MB
730. 745.csv — 1.07 MB
731. 70.csv — 1.12 MB
732. 710.csv — 0.93 MB
733. 780.csv — 0.99 MB
734. 791.csv — 1.04 MB
735. 717.csv — 1.16 MB
736. 75.csv — 1.17 MB
737. 79.csv — 0.84 MB
738. 748.csv — 1.09 MB
739. 744.csv — 1.04 MB
740. 777.csv — 0.98 MB
741. 754.csv — 0.66 MB
742. 764.csv — 0.98 MB
743. 765.csv — 0.98 MB
744. 763.csv — 1.02 MB
745. 751.csv — 1.10 MB
746. 779.csv — 1.06 MB
747. 76.csv — 1.08 MB
748. 716.csv — 0.89 MB
749. 741.csv — 1.04 MB
750. 757.csv — 0.72 MB
751. 720.csv — 0.87 MB
752. 746.csv — 1.09 MB
753. 796.csv — 0.92 MB
754. 753.csv — 0.00 MB
755. 736.csv — 0.98 MB
756. 778.csv — 0.97 MB
757. 749.csv — 1.07 MB
758. 714.csv — 0.87 MB
759. 72.csv — 1.37 MB
760. 774.csv — 1.09 MB
761. 794.csv — 1.19 MB
762. 718.csv — 1.12 MB
763. 750.csv — 1.07 MB
764. 747.csv — 1.09 MB
765. 768.csv — 1.15 MB
766. 762.csv — 0.89 MB
767. 740.csv — 1.08 MB
768. 721.csv — 1.04 MB
769. 793.csv — 0.95 MB
770. 702.csv — 1.01 MB
771. 705.csv — 0.99 MB
772. 723.csv — 1.22 MB
773. 700.csv — 0.00 MB
774. 776.csv — 1.06 MB
775. 726.csv — 0.87 MB
776. 889.csv — 0.90 MB
777. 820.csv — 1.03 MB
778. 845.csv — 1.11 MB
779. 863.csv — 0.91 MB
780. 850.csv — 1.23 MB
781. 852.csv — 1.10 MB
782. 860.csv — 1.04 MB
783. 827.csv — 1.13 MB
784. 849.csv — 0.83 MB
785. 884.csv — 1.24 MB
786. 814.csv — 1.11 MB
787. 839.csv — 1.02 MB
788. 86.csv — 1.11 MB
789. 88.csv — 1.04 MB
790. 876.csv — 1.09 MB
791. 864.csv — 1.13 MB
792. 841.csv — 0.78 MB
793. 853.csv — 1.06 MB
794. 834.csv — 0.87 MB
795. 848.csv — 0.91 MB
796. 855.csv — 1.07 MB
797. 831.csv — 0.73 MB
798. 885.csv — 1.18 MB
799. 821.csv — 1.05 MB
800. 851.csv — 0.99 MB
801. 846.csv — 1.07 MB
802. 859.csv — 0.90 MB
803. 805.csv — 1.01 MB
804. 812.csv — 1.13 MB
805. 872.csv — 1.05 MB
806. 835.csv — 1.10 MB
807. 873.csv — 1.02 MB
808. 813.csv — 0.78 MB
809. 888.csv — 0.96 MB
810. 874.csv — 1.21 MB
811. 804.csv — 0.64 MB
812. 803.csv — 0.91 MB
813. 810.csv — 1.27 MB
814. 883.csv — 0.96 MB
815. 829.csv — 0.98 MB
816. 828.csv — 1.07 MB
817. 890.csv — 1.26 MB
818. 809.csv — 1.26 MB
819. 882.csv — 1.14 MB
820. 816.csv — 1.06 MB
821. 811.csv — 0.51 MB
822. 807.csv — 1.40 MB
823. 836.csv — 1.00 MB
824. 84.csv — 1.13 MB
825. 830.csv — 0.96 MB
826. 861.csv — 1.08 MB
827. 89.csv — 1.05 MB
828. 866.csv — 0.86 MB
829. 85.csv — 1.09 MB
830. 87.csv — 0.51 MB
831. 862.csv — 0.88 MB
832. 797.csv — 0.75 MB
833. 799.csv — 0.96 MB
834. 822.csv — 1.08 MB
835. 842.csv — 1.41 MB
836. 844.csv — 1.39 MB
837. 81.csv — 1.12 MB
838. 887.csv — 0.70 MB
839. 824.csv — 0.94 MB
840. 823.csv — 1.15 MB
841. 806.csv — 0.51 MB
842. 826.csv — 1.07 MB
843. 854.csv — 1.03 MB
844. 808.csv — 0.98 MB
845. 832.csv — 0.91 MB
846. 871.csv — 1.26 MB
847. 847.csv — 0.67 MB
848. 82.csv — 1.36 MB
849. 875.csv — 1.22 MB
850. 868.csv — 1.22 MB
851. 833.csv — 0.87 MB
852. 843.csv — 0.80 MB
853. 83.csv — 0.23 MB
854. 837.csv — 0.67 MB
855. 879.csv — 1.23 MB
856. 817.csv — 1.08 MB
857. 800.csv — 0.90 MB
858. 880.csv — 1.19 MB
859. 840.csv — 0.79 MB
860. 886.csv — 1.06 MB
861. 869.csv — 1.22 MB
862. 856.csv — 1.16 MB
863. 815.csv — 1.08 MB
864. 8.csv — 0.93 MB
865. 877.csv — 1.12 MB
866. 818.csv — 1.01 MB
867. 80.csv — 1.21 MB
868. 867.csv — 1.23 MB
869. 858.csv — 1.16 MB
870. 801.csv — 1.12 MB
871. 857.csv — 0.98 MB
872. 878.csv — 0.99 MB
873. 802.csv — 1.00 MB
874. 870.csv — 1.22 MB
875. 825.csv — 1.09 MB

In [ ]:
for file in bitbrains_files:
    print(file.name, "→", file.suffix.lower())

1.csv → .csv
10.csv → .csv
100.csv → .csv
1000.csv → .csv
1001.csv → .csv
1002.csv → .csv
1003.csv → .csv
1004.csv → .csv
1005.csv → .csv
1006.csv → .csv
1007.csv → .csv
1008.csv → .csv
1009.csv → .csv
101.csv → .csv
1010.csv → .csv
1011.csv → .csv
1012.csv → .csv
1013.csv → .csv
1014.csv → .csv
1015.csv → .csv
1016.csv → .csv
1017.csv → .csv
1018.csv → .csv
1019.csv → .csv
102.csv → .csv
1020.csv → .csv
1021.csv → .csv
1022.csv → .csv
1023.csv → .csv
1024.csv → .csv
1025.csv → .csv
1026.csv → .csv
1027.csv → .csv
1028.csv → .csv
1029.csv → .csv
103.csv → .csv
1030.csv → .csv
1031.csv → .csv
1032.csv → .csv
1033.csv → .csv
1034.csv → .csv
1035.csv → .csv
1036.csv → .csv
1037.csv → .csv
1038.csv → .csv
1039.csv → .csv
104.csv → .csv
1040.csv → .csv
1041.csv → .csv
1042.csv → .csv
1043.csv → .csv
1044.csv → .csv
1045.csv → .csv
1046.csv → .csv
1047.csv → .csv
1048.csv → .csv
1049.csv → .csv
105.csv → .csv
1050.csv → .csv
1051.csv → .csv
1052.csv → .csv
1053.csv → .csv
1054.csv → .csv
1055.csv → .csv
1056.csv → .csv
1057.csv → .csv
1058.csv → .csv
1059.csv → .csv
106.csv → .csv
1060.csv → .csv
1061.csv → .csv
1062.csv → .csv
1063.csv → .csv
1064.csv → .csv
1065.csv → .csv
1066.csv → .csv
1067.csv → .csv
1068.csv → .csv
1069.csv → .csv
107.csv → .csv
1070.csv → .csv
1071.csv → .csv
1072.csv → .csv
1073.csv → .csv
1074.csv → .csv
1075.csv → .csv
1076.csv → .csv
1077.csv → .csv
1078.csv → .csv
1079.csv → .csv
108.csv → .csv
1080.csv → .csv
1081.csv → .csv
1082.csv → .csv
1083.csv → .csv
1084.csv → .csv
1085.csv → .csv
1086.csv → .csv
1087.csv → .csv
1088.csv → .csv
1089.csv → .csv
109.csv → .csv
1090.csv → .csv
1091.csv → .csv
1092.csv → .csv
1093.csv → .csv
1094.csv → .csv
1095.csv → .csv
1096.csv → .csv
1097.csv → .csv
1098.csv → .csv
1099.csv → .csv
11.csv → .csv
110.csv → .csv
1100.csv → .csv
1101.csv → .csv
1102.csv → .csv
1103.csv → .csv
1104.csv → .csv
1105.csv → .csv
1106.csv → .csv
1107.csv → .csv
1108.csv → .csv
1109.csv → .csv
111.csv → .csv
1110.csv → .csv
1111.csv → .csv
1112.csv → .csv
1113.csv → .csv
1114.csv → .csv
1115.csv → .csv
1116.csv → .csv
1117.csv → .csv
1118.csv → .csv
1119.csv → .csv
112.csv → .csv
1120.csv → .csv
1121.csv → .csv
1122.csv → .csv
1123.csv → .csv
1124.csv → .csv
1125.csv → .csv
1126.csv → .csv
1127.csv → .csv
1128.csv → .csv
1129.csv → .csv
113.csv → .csv
1130.csv → .csv
1131.csv → .csv
1132.csv → .csv
1133.csv → .csv
1134.csv → .csv
1135.csv → .csv
1136.csv → .csv
1137.csv → .csv
1138.csv → .csv
1139.csv → .csv
114.csv → .csv
1140.csv → .csv
1141.csv → .csv
1142.csv → .csv
1143.csv → .csv
1144.csv → .csv
1145.csv → .csv
1146.csv → .csv
1147.csv → .csv
1148.csv → .csv
1149.csv → .csv
115.csv → .csv
1150.csv → .csv
1151.csv → .csv
1152.csv → .csv
1153.csv → .csv
1154.csv → .csv
1155.csv → .csv
1156.csv → .csv
1157.csv → .csv
1158.csv → .csv
1159.csv → .csv
116.csv → .csv
1160.csv → .csv
1161.csv → .csv
1162.csv → .csv
1163.csv → .csv
1164.csv → .csv
1165.csv → .csv
1166.csv → .csv
1167.csv → .csv
1168.csv → .csv
1169.csv → .csv
117.csv → .csv
1170.csv → .csv
1171.csv → .csv
1172.csv → .csv
1173.csv → .csv
1174.csv → .csv
1175.csv → .csv
1176.csv → .csv
1177.csv → .csv
1178.csv → .csv
1179.csv → .csv
118.csv → .csv
1180.csv → .csv
1181.csv → .csv
1182.csv → .csv
1183.csv → .csv
1184.csv → .csv
1185.csv → .csv
1186.csv → .csv
1187.csv → .csv
1188.csv → .csv
1189.csv → .csv
119.csv → .csv
1190.csv → .csv
1191.csv → .csv
1192.csv → .csv
1193.csv → .csv
1194.csv → .csv
1195.csv → .csv
1196.csv → .csv
1197.csv → .csv
1198.csv → .csv
1199.csv → .csv
12.csv → .csv
120.csv → .csv
1200.csv → .csv
1201.csv → .csv
1202.csv → .csv
1203.csv → .csv
1204.csv → .csv
1205.csv → .csv
1206.csv → .csv
1207.csv → .csv
1208.csv → .csv
1209.csv → .csv
121.csv → .csv
1210.csv → .csv
1211.csv → .csv
1212.csv → .csv
1213.csv → .csv
1214.csv → .csv
1215.csv → .csv
1216.csv → .csv
1217.csv → .csv
1218.csv → .csv
1219.csv → .csv
122.csv → .csv
1220.csv → .csv
1221.csv → .csv
1222.csv → .csv
1223.csv → .csv
1224.csv → .csv
1225.csv → .csv
1226.csv → .csv
1227.csv → .csv
1228.csv → .csv
1229.csv → .csv
123.csv → .csv
1230.csv → .csv
1231.csv → .csv
1232.csv → .csv
1233.csv → .csv
1234.csv → .csv
1235.csv → .csv
1236.csv → .csv
1237.csv → .csv
1238.csv → .csv
1239.csv → .csv
124.csv → .csv
1240.csv → .csv
1241.csv → .csv
1242.csv → .csv
1243.csv → .csv
1244.csv → .csv
1245.csv → .csv
1246.csv → .csv
1247.csv → .csv
1248.csv → .csv
1249.csv → .csv
125.csv → .csv
1250.csv → .csv
126.csv → .csv
127.csv → .csv
128.csv → .csv
129.csv → .csv
13.csv → .csv
130.csv → .csv
131.csv → .csv
132.csv → .csv
133.csv → .csv
134.csv → .csv
135.csv → .csv
136.csv → .csv
137.csv → .csv
138.csv → .csv
139.csv → .csv
14.csv → .csv
140.csv → .csv
141.csv → .csv
142.csv → .csv
143.csv → .csv
144.csv → .csv
145.csv → .csv
146.csv → .csv
147.csv → .csv
148.csv → .csv
149.csv → .csv
15.csv → .csv
150.csv → .csv
151.csv → .csv
152.csv → .csv
153.csv → .csv
154.csv → .csv
155.csv → .csv
156.csv → .csv
157.csv → .csv
158.csv → .csv
159.csv → .csv
16.csv → .csv
160.csv → .csv
161.csv → .csv
162.csv → .csv
163.csv → .csv
164.csv → .csv
165.csv → .csv
166.csv → .csv
167.csv → .csv
168.csv → .csv
169.csv → .csv
17.csv → .csv
170.csv → .csv
171.csv → .csv
172.csv → .csv
173.csv → .csv
174.csv → .csv
175.csv → .csv
176.csv → .csv
177.csv → .csv
178.csv → .csv
179.csv → .csv
18.csv → .csv
180.csv → .csv
181.csv → .csv
182.csv → .csv
183.csv → .csv
184.csv → .csv
185.csv → .csv
186.csv → .csv
187.csv → .csv
188.csv → .csv
189.csv → .csv
19.csv → .csv
190.csv → .csv
191.csv → .csv
192.csv → .csv
193.csv → .csv
194.csv → .csv
195.csv → .csv
196.csv → .csv
197.csv → .csv
198.csv → .csv
199.csv → .csv
2.csv → .csv
20.csv → .csv
200.csv → .csv
201.csv → .csv
202.csv → .csv
203.csv → .csv
204.csv → .csv
205.csv → .csv
206.csv → .csv
207.csv → .csv
208.csv → .csv
209.csv → .csv
21.csv → .csv
210.csv → .csv
211.csv → .csv
212.csv → .csv
213.csv → .csv
214.csv → .csv
215.csv → .csv
216.csv → .csv
217.csv → .csv
218.csv → .csv
219.csv → .csv
22.csv → .csv
220.csv → .csv
221.csv → .csv
222.csv → .csv
223.csv → .csv
224.csv → .csv
225.csv → .csv
226.csv → .csv
227.csv → .csv
228.csv → .csv
229.csv → .csv
23.csv → .csv
230.csv → .csv
231.csv → .csv
232.csv → .csv
233.csv → .csv
234.csv → .csv
235.csv → .csv
236.csv → .csv
237.csv → .csv
238.csv → .csv
239.csv → .csv
24.csv → .csv
240.csv → .csv
241.csv → .csv
242.csv → .csv
243.csv → .csv
244.csv → .csv
245.csv → .csv
246.csv → .csv
247.csv → .csv
248.csv → .csv
249.csv → .csv
25.csv → .csv
250.csv → .csv
251.csv → .csv
252.csv → .csv
253.csv → .csv
254.csv → .csv
255.csv → .csv
256.csv → .csv
257.csv → .csv
258.csv → .csv
259.csv → .csv
26.csv → .csv
260.csv → .csv
261.csv → .csv
262.csv → .csv
263.csv → .csv
264.csv → .csv
265.csv → .csv
266.csv → .csv
267.csv → .csv
268.csv → .csv
269.csv → .csv
27.csv → .csv
270.csv → .csv
271.csv → .csv
272.csv → .csv
273.csv → .csv
274.csv → .csv
275.csv → .csv
276.csv → .csv
277.csv → .csv
278.csv → .csv
279.csv → .csv
28.csv → .csv
280.csv → .csv
281.csv → .csv
282.csv → .csv
283.csv → .csv
284.csv → .csv
285.csv → .csv
286.csv → .csv
287.csv → .csv
288.csv → .csv
289.csv → .csv
29.csv → .csv
290.csv → .csv
291.csv → .csv
292.csv → .csv
293.csv → .csv
294.csv → .csv
295.csv → .csv
296.csv → .csv
297.csv → .csv
298.csv → .csv
299.csv → .csv
3.csv → .csv
30.csv → .csv
300.csv → .csv
301.csv → .csv
302.csv → .csv
303.csv → .csv
304.csv → .csv
305.csv → .csv
306.csv → .csv
307.csv → .csv
308.csv → .csv
309.csv → .csv
31.csv → .csv
310.csv → .csv
311.csv → .csv
312.csv → .csv
313.csv → .csv
314.csv → .csv
315.csv → .csv
316.csv → .csv
317.csv → .csv
318.csv → .csv
319.csv → .csv
32.csv → .csv
320.csv → .csv
321.csv → .csv
322.csv → .csv
323.csv → .csv
324.csv → .csv
325.csv → .csv
326.csv → .csv
327.csv → .csv
328.csv → .csv
329.csv → .csv
33.csv → .csv
330.csv → .csv
331.csv → .csv
332.csv → .csv
333.csv → .csv
334.csv → .csv
335.csv → .csv
336.csv → .csv
337.csv → .csv
338.csv → .csv
339.csv → .csv
34.csv → .csv
340.csv → .csv
341.csv → .csv
342.csv → .csv
343.csv → .csv
344.csv → .csv
345.csv → .csv
346.csv → .csv
347.csv → .csv
348.csv → .csv
349.csv → .csv
35.csv → .csv
350.csv → .csv
351.csv → .csv
352.csv → .csv
353.csv → .csv
354.csv → .csv
355.csv → .csv
356.csv → .csv
357.csv → .csv
358.csv → .csv
359.csv → .csv
36.csv → .csv
360.csv → .csv
361.csv → .csv
362.csv → .csv
363.csv → .csv
364.csv → .csv
365.csv → .csv
366.csv → .csv
367.csv → .csv
368.csv → .csv
369.csv → .csv
37.csv → .csv
370.csv → .csv
371.csv → .csv
372.csv → .csv
373.csv → .csv
374.csv → .csv
375.csv → .csv
376.csv → .csv
377.csv → .csv
378.csv → .csv
379.csv → .csv
38.csv → .csv
380.csv → .csv
381.csv → .csv
382.csv → .csv
383.csv → .csv
384.csv → .csv
385.csv → .csv
386.csv → .csv
387.csv → .csv
388.csv → .csv
389.csv → .csv
39.csv → .csv
390.csv → .csv
391.csv → .csv
392.csv → .csv
393.csv → .csv
394.csv → .csv
395.csv → .csv
396.csv → .csv
397.csv → .csv
398.csv → .csv
399.csv → .csv
4.csv → .csv
40.csv → .csv
400.csv → .csv
401.csv → .csv
402.csv → .csv
403.csv → .csv
404.csv → .csv
405.csv → .csv
406.csv → .csv
407.csv → .csv
408.csv → .csv
409.csv → .csv
41.csv → .csv
410.csv → .csv
411.csv → .csv
412.csv → .csv
413.csv → .csv
414.csv → .csv
415.csv → .csv
416.csv → .csv
417.csv → .csv
418.csv → .csv
419.csv → .csv
42.csv → .csv
420.csv → .csv
421.csv → .csv
422.csv → .csv
423.csv → .csv
424.csv → .csv
425.csv → .csv
426.csv → .csv
427.csv → .csv
428.csv → .csv
429.csv → .csv
43.csv → .csv
430.csv → .csv
431.csv → .csv
432.csv → .csv
433.csv → .csv
434.csv → .csv
435.csv → .csv
436.csv → .csv
437.csv → .csv
438.csv → .csv
439.csv → .csv
44.csv → .csv
440.csv → .csv
441.csv → .csv
442.csv → .csv
443.csv → .csv
444.csv → .csv
445.csv → .csv
446.csv → .csv
447.csv → .csv
448.csv → .csv
449.csv → .csv
45.csv → .csv
450.csv → .csv
451.csv → .csv
452.csv → .csv
453.csv → .csv
454.csv → .csv
455.csv → .csv
456.csv → .csv
457.csv → .csv
458.csv → .csv
459.csv → .csv
46.csv → .csv
460.csv → .csv
461.csv → .csv
462.csv → .csv
463.csv → .csv
464.csv → .csv
465.csv → .csv
466.csv → .csv
467.csv → .csv
468.csv → .csv
469.csv → .csv
47.csv → .csv
470.csv → .csv
471.csv → .csv
472.csv → .csv
473.csv → .csv
474.csv → .csv
475.csv → .csv
476.csv → .csv
477.csv → .csv
478.csv → .csv
479.csv → .csv
48.csv → .csv
480.csv → .csv
481.csv → .csv
482.csv → .csv
483.csv → .csv
484.csv → .csv
485.csv → .csv
486.csv → .csv
487.csv → .csv
488.csv → .csv
489.csv → .csv
49.csv → .csv
490.csv → .csv
491.csv → .csv
492.csv → .csv
493.csv → .csv
494.csv → .csv
495.csv → .csv
496.csv → .csv
497.csv → .csv
498.csv → .csv
499.csv → .csv
5.csv → .csv
50.csv → .csv
500.csv → .csv
501.csv → .csv
502.csv → .csv
503.csv → .csv
504.csv → .csv
505.csv → .csv
506.csv → .csv
507.csv → .csv
508.csv → .csv
509.csv → .csv
51.csv → .csv
510.csv → .csv
511.csv → .csv
512.csv → .csv
513.csv → .csv
514.csv → .csv
515.csv → .csv
516.csv → .csv
517.csv → .csv
518.csv → .csv
519.csv → .csv
52.csv → .csv
520.csv → .csv
521.csv → .csv
522.csv → .csv
523.csv → .csv
524.csv → .csv
525.csv → .csv
526.csv → .csv
527.csv → .csv
528.csv → .csv
529.csv → .csv
53.csv → .csv
530.csv → .csv
531.csv → .csv
532.csv → .csv
533.csv → .csv
534.csv → .csv
535.csv → .csv
536.csv → .csv
537.csv → .csv
538.csv → .csv
539.csv → .csv
54.csv → .csv
540.csv → .csv
541.csv → .csv
542.csv → .csv
543.csv → .csv
544.csv → .csv
545.csv → .csv
546.csv → .csv
547.csv → .csv
548.csv → .csv
549.csv → .csv
55.csv → .csv
550.csv → .csv
551.csv → .csv
552.csv → .csv
553.csv → .csv
554.csv → .csv
555.csv → .csv
556.csv → .csv
557.csv → .csv
558.csv → .csv
559.csv → .csv
56.csv → .csv
560.csv → .csv
561.csv → .csv
562.csv → .csv
563.csv → .csv
564.csv → .csv
565.csv → .csv
566.csv → .csv
567.csv → .csv
568.csv → .csv
569.csv → .csv
57.csv → .csv
570.csv → .csv
571.csv → .csv
572.csv → .csv
573.csv → .csv
574.csv → .csv
575.csv → .csv
576.csv → .csv
577.csv → .csv
578.csv → .csv
579.csv → .csv
58.csv → .csv
580.csv → .csv
581.csv → .csv
582.csv → .csv
583.csv → .csv
584.csv → .csv
585.csv → .csv
586.csv → .csv
587.csv → .csv
588.csv → .csv
589.csv → .csv
59.csv → .csv
590.csv → .csv
591.csv → .csv
592.csv → .csv
593.csv → .csv
594.csv → .csv
595.csv → .csv
596.csv → .csv
597.csv → .csv
598.csv → .csv
599.csv → .csv
6.csv → .csv
60.csv → .csv
600.csv → .csv
601.csv → .csv
602.csv → .csv
603.csv → .csv
604.csv → .csv
605.csv → .csv
606.csv → .csv
607.csv → .csv
608.csv → .csv
609.csv → .csv
61.csv → .csv
610.csv → .csv
611.csv → .csv
612.csv → .csv
613.csv → .csv
614.csv → .csv
615.csv → .csv
616.csv → .csv
617.csv → .csv
618.csv → .csv
619.csv → .csv
62.csv → .csv
620.csv → .csv
621.csv → .csv
622.csv → .csv
623.csv → .csv
624.csv → .csv
625.csv → .csv
626.csv → .csv
627.csv → .csv
628.csv → .csv
629.csv → .csv
63.csv → .csv
630.csv → .csv
631.csv → .csv
632.csv → .csv
633.csv → .csv
634.csv → .csv
635.csv → .csv
636.csv → .csv
637.csv → .csv
638.csv → .csv
639.csv → .csv
64.csv → .csv
640.csv → .csv
641.csv → .csv
642.csv → .csv
643.csv → .csv
644.csv → .csv
645.csv → .csv
646.csv → .csv
647.csv → .csv
648.csv → .csv
649.csv → .csv
65.csv → .csv
650.csv → .csv
651.csv → .csv
652.csv → .csv
653.csv → .csv
654.csv → .csv
655.csv → .csv
656.csv → .csv
657.csv → .csv
658.csv → .csv
659.csv → .csv
66.csv → .csv
660.csv → .csv
661.csv → .csv
662.csv → .csv
663.csv → .csv
664.csv → .csv
665.csv → .csv
666.csv → .csv
667.csv → .csv
668.csv → .csv
669.csv → .csv
67.csv → .csv
670.csv → .csv
671.csv → .csv
672.csv → .csv
673.csv → .csv
674.csv → .csv
675.csv → .csv
676.csv → .csv
677.csv → .csv
678.csv → .csv
679.csv → .csv
68.csv → .csv
680.csv → .csv
681.csv → .csv
682.csv → .csv
683.csv → .csv
684.csv → .csv
685.csv → .csv
686.csv → .csv
687.csv → .csv
688.csv → .csv
689.csv → .csv
69.csv → .csv
690.csv → .csv
691.csv → .csv
692.csv → .csv
693.csv → .csv
694.csv → .csv
695.csv → .csv
696.csv → .csv
697.csv → .csv
698.csv → .csv
699.csv → .csv
7.csv → .csv
70.csv → .csv
700.csv → .csv
701.csv → .csv
702.csv → .csv
703.csv → .csv
704.csv → .csv
705.csv → .csv
706.csv → .csv
707.csv → .csv
708.csv → .csv
709.csv → .csv
71.csv → .csv
710.csv → .csv
711.csv → .csv
712.csv → .csv
713.csv → .csv
714.csv → .csv
715.csv → .csv
716.csv → .csv
717.csv → .csv
718.csv → .csv
719.csv → .csv
72.csv → .csv
720.csv → .csv
721.csv → .csv
722.csv → .csv
723.csv → .csv
724.csv → .csv
725.csv → .csv
726.csv → .csv
727.csv → .csv
728.csv → .csv
729.csv → .csv
73.csv → .csv
730.csv → .csv
731.csv → .csv
732.csv → .csv
733.csv → .csv
734.csv → .csv
735.csv → .csv
736.csv → .csv
737.csv → .csv
738.csv → .csv
739.csv → .csv
74.csv → .csv
740.csv → .csv
741.csv → .csv
742.csv → .csv
743.csv → .csv
744.csv → .csv
745.csv → .csv
746.csv → .csv
747.csv → .csv
748.csv → .csv
749.csv → .csv
75.csv → .csv
750.csv → .csv
751.csv → .csv
752.csv → .csv
753.csv → .csv
754.csv → .csv
755.csv → .csv
756.csv → .csv
757.csv → .csv
758.csv → .csv
759.csv → .csv
76.csv → .csv
760.csv → .csv
761.csv → .csv
762.csv → .csv
763.csv → .csv
764.csv → .csv
765.csv → .csv
766.csv → .csv
767.csv → .csv
768.csv → .csv
769.csv → .csv
77.csv → .csv
770.csv → .csv
771.csv → .csv
772.csv → .csv
773.csv → .csv
774.csv → .csv
775.csv → .csv
776.csv → .csv
777.csv → .csv
778.csv → .csv
779.csv → .csv
78.csv → .csv
780.csv → .csv
781.csv → .csv
782.csv → .csv
783.csv → .csv
784.csv → .csv
785.csv → .csv
786.csv → .csv
787.csv → .csv
788.csv → .csv
789.csv → .csv
79.csv → .csv
790.csv → .csv
791.csv → .csv
792.csv → .csv
793.csv → .csv
794.csv → .csv
795.csv → .csv
796.csv → .csv
797.csv → .csv
798.csv → .csv
799.csv → .csv
8.csv → .csv
80.csv → .csv
800.csv → .csv
801.csv → .csv
802.csv → .csv
803.csv → .csv
804.csv → .csv
805.csv → .csv
806.csv → .csv
807.csv → .csv
808.csv → .csv
809.csv → .csv
81.csv → .csv
810.csv → .csv
811.csv → .csv
812.csv → .csv
813.csv → .csv
814.csv → .csv
815.csv → .csv
816.csv → .csv
817.csv → .csv
818.csv → .csv
819.csv → .csv
82.csv → .csv
820.csv → .csv
821.csv → .csv
822.csv → .csv
823.csv → .csv
824.csv → .csv
825.csv → .csv
826.csv → .csv
827.csv → .csv
828.csv → .csv
829.csv → .csv
83.csv → .csv
830.csv → .csv
831.csv → .csv
832.csv → .csv
833.csv → .csv
834.csv → .csv
835.csv → .csv
836.csv → .csv
837.csv → .csv
838.csv → .csv
839.csv → .csv
84.csv → .csv
840.csv → .csv
841.csv → .csv
842.csv → .csv
843.csv → .csv
844.csv → .csv
845.csv → .csv
846.csv → .csv
847.csv → .csv
848.csv → .csv
849.csv → .csv
85.csv → .csv
850.csv → .csv
851.csv → .csv
852.csv → .csv
853.csv → .csv
854.csv → .csv
855.csv → .csv
856.csv → .csv
857.csv → .csv
858.csv → .csv
859.csv → .csv
86.csv → .csv
860.csv → .csv
861.csv → .csv
862.csv → .csv
863.csv → .csv
864.csv → .csv
865.csv → .csv
866.csv → .csv
867.csv → .csv
868.csv → .csv
869.csv → .csv
87.csv → .csv
870.csv → .csv
871.csv → .csv
872.csv → .csv
873.csv → .csv
874.csv → .csv
875.csv → .csv
876.csv → .csv
877.csv → .csv
878.csv → .csv
879.csv → .csv
88.csv → .csv
880.csv → .csv
881.csv → .csv
882.csv → .csv
883.csv → .csv
884.csv → .csv
885.csv → .csv
886.csv → .csv
887.csv → .csv
888.csv → .csv
889.csv → .csv
89.csv → .csv
890.csv → .csv
891.csv → .csv
892.csv → .csv
893.csv → .csv
894.csv → .csv
895.csv → .csv
896.csv → .csv
897.csv → .csv
898.csv → .csv
899.csv → .csv
9.csv → .csv
90.csv → .csv
900.csv → .csv
901.csv → .csv
902.csv → .csv
903.csv → .csv
904.csv → .csv
905.csv → .csv
906.csv → .csv
907.csv → .csv
908.csv → .csv
909.csv → .csv
91.csv → .csv
910.csv → .csv
911.csv → .csv
912.csv → .csv
913.csv → .csv
914.csv → .csv
915.csv → .csv
916.csv → .csv
917.csv → .csv
918.csv → .csv
919.csv → .csv
92.csv → .csv
920.csv → .csv
921.csv → .csv
922.csv → .csv
923.csv → .csv
924.csv → .csv
925.csv → .csv
926.csv → .csv
927.csv → .csv
928.csv → .csv
929.csv → .csv
93.csv → .csv
930.csv → .csv
931.csv → .csv
932.csv → .csv
933.csv → .csv
934.csv → .csv
935.csv → .csv
936.csv → .csv
937.csv → .csv
938.csv → .csv
939.csv → .csv
94.csv → .csv
940.csv → .csv
941.csv → .csv
942.csv → .csv
943.csv → .csv
944.csv → .csv
945.csv → .csv
946.csv → .csv
947.csv → .csv
948.csv → .csv
949.csv → .csv
95.csv → .csv
950.csv → .csv
951.csv → .csv
952.csv → .csv
953.csv → .csv
954.csv → .csv
955.csv → .csv
956.csv → .csv
957.csv → .csv
958.csv → .csv
959.csv → .csv
96.csv → .csv
960.csv → .csv
961.csv → .csv
962.csv → .csv
963.csv → .csv
964.csv → .csv
965.csv → .csv
966.csv → .csv
967.csv → .csv
968.csv → .csv
969.csv → .csv
97.csv → .csv
970.csv → .csv
971.csv → .csv
972.csv → .csv
973.csv → .csv
974.csv → .csv
975.csv → .csv
976.csv → .csv
977.csv → .csv
978.csv → .csv
979.csv → .csv
98.csv → .csv
980.csv → .csv
981.csv → .csv
982.csv → .csv
983.csv → .csv
984.csv → .csv
985.csv → .csv
986.csv → .csv
987.csv → .csv
988.csv → .csv
989.csv → .csv
99.csv → .csv
990.csv → .csv
991.csv → .csv
992.csv → .csv
993.csv → .csv
994.csv → .csv
995.csv → .csv
996.csv → .csv
997.csv → .csv
998.csv → .csv
999.csv → .csv

In [ ]:
csv_files = [
    f for f in bitbrains_files
    if f.suffix.lower() == ".csv"
]

if csv_files:
    for file in csv_files:
        print(f"\n===== {file.name} =====")

        with open(file, "r", encoding="utf-8", errors="ignore") as f:
            for _ in range(5):
                print(f.readline().strip())
else:
    print("No CSV files found.")

Streaming output truncated to the last 5000 lines.
1376315446;	1;	2599.99945;	19.06666263333333;	0.7333333333333333;	4194304.0;	106254.13333333333;	0.0;	1.0;	0.06666666666666667;	0.2
1376315746;	1;	2599.99945;	17.333329666666668;	0.6666666666666667;	4194304.0;	156586.13333333333;	0.0;	1.2;	0.0;	0.06666666666666667

===== 356.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	1;	2599.999334;	17.333328893333338;	0.6666666666666667;	4194304.0;	176157.86666666667;	0.0;	1.4666666666666666;	0.06666666666666667;	0.0
1376315146;	1;	2599.999334;	13.866663114666666;	0.5333333333333333;	4194304.0;	78291.46666666666;	0.0;	1.3333333333333333;	0.0;	0.0
1376315446;	1;	2599.999334;	15.599996004;	0.6;	4194304.0;	95069.06666666667;	0.0;	1.4666666666666666;	0.0;	0.0
1376315746;	1;	2599.999334;	17.333328893333338;	0.6666666666666667;	4194304.0;	55922.13333333333;	0.0;	2.2666666666666666;	0.2;	0.13333333333333333

===== 357.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	6;	15599.995728;	221.86660590933334;	1.4222222222222223;	1.2582912E7;	1442838.6666666667;	0.9333333333333333;	10.666666666666668;	56.53333333333333;	106.2
1376315146;	6;	15599.995728;	688.1331448906666;	4.4111111111111105;	1.2582912E7;	763361.3333333334;	380.0;	53.53333333333334;	311.73333333333335;	5479.8
1376315446;	6;	15599.995728;	284.2665888213333;	1.822222222222222;	1.2582912E7;	629143.4666666667;	0.9333333333333333;	4.4;	138.26666666666668;	194.8
1376315746;	6;	15599.995728;	284.2665888213333;	1.822222222222222;	1.2582912E7;	411039.2;	6.266666666666667;	41.266666666666666;	112.4;	1591.1333333333334

===== 358.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	1;	2599.998966;	0.0;	0.0;	4114432.0;	117439.2;	0.0;	0.0;	0.2;	1.1333333333333333
1376315146;	1;	2599.998966;	0.0;	0.0;	4114432.0;	83884.0;	0.0;	0.4666666666666667;	0.0;	1.1333333333333333
1376315446;	1;	2599.998966;	0.0;	0.0;	4114432.0;	72698.93333333333;	0.0;	0.0;	0.06666666666666667;	1.1333333333333333
1376315746;	1;	2599.998966;	0.0;	0.0;	4114432.0;	41940.0;	0.0;	0.0;	0.06666666666666667;	1.1333333333333333

===== 359.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	4;	10399.997204;	81.46664476466667;	0.7833333333333333;	8060308.0;	150993.6;	12.6;	13.066666666666666;	0.0;	0.0
1376315146;	4;	10399.997204;	76.26664616266666;	0.7333333333333333;	8060308.0;	139809.06666666668;	12.933333333333334;	13.4;	0.06666666666666667;	0.06666666666666667
1376315446;	4;	10399.997204;	79.73331189733334;	0.7666666666666667;	8060308.0;	111846.13333333333;	13.0;	13.533333333333333;	0.0;	0.0
1376315746;	4;	10399.997204;	83.19997763199999;	0.8;	8060308.0;	83884.0;	23.0;	14.2;	0.06666666666666667;	0.06666666666666667

===== 36.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	1;	2599.999309;	25.999993089999997;	1.0;	702948.0;	54523.2;	0.0;	4.2;	1.0;	1.0
1376315146;	1;	2599.999309;	25.999993089999997;	1.0;	702948.0;	88078.4;	0.0;	4.266666666666667;	1.0;	1.0
1376315446;	1;	2599.999309;	25.999993089999997;	1.0;	702948.0;	99263.46666666666;	0.0;	4.0;	1.0;	1.0
1376315746;	1;	2599.999309;	25.999993089999997;	1.0;	702948.0;	57319.46666666667;	0.0;	4.2;	1.0;	1.0

===== 360.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.9986;	752.2664641333333;	14.466666666666667;	8388608.0;	3260370.4;	114.8;	596.4666666666667;	6.8;	5.4
1376315146;	2;	5199.9986;	289.4665887333333;	5.566666666666666;	8388608.0;	3159708.0;	50.86666666666667;	442.8666666666667;	6.666666666666667;	5.133333333333334
1376315446;	2;	5199.9986;	759.1997955999999;	14.6;	8388608.0;	3439326.6666666665;	111.2;	592.4666666666666;	7.6;	5.866666666666666
1376315746;	2;	5199.9986;	296.3999202;	5.7;	8388608.0;	3232408.533333333;	48.13333333333333;	603.3333333333334;	6.533333333333333;	5.333333333333333

===== 361.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.999234;	643.0665719379999;	12.366666666666667;	4194304.0;	343931.2;	0.0;	28.733333333333334;	0.4666666666666667;	0.0
1376315146;	2;	5199.999234;	646.5332380939999;	12.433333333333332;	4194304.0;	419428.26666666666;	0.0;	30.133333333333333;	0.5333333333333333;	0.0
1376315446;	2;	5199.999234;	623.9999080800001;	12.0;	4194304.0;	279618.6666666667;	0.0;	28.666666666666668;	0.3333333333333333;	0.0
1376315746;	2;	5199.999234;	630.9332403919999;	12.133333333333333;	4194304.0;	282414.93333333335;	0.0;	31.133333333333333;	0.3333333333333333;	0.0

===== 362.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.999204;	77.99998805999999;	1.5;	481280.0;	11182.933333333332;	0.0;	0.9333333333333333;	0.0;	0.0
1376315146;	2;	5199.999204;	77.99998805999999;	1.5;	481280.0;	8387.2;	0.0;	0.5333333333333333;	0.0;	0.0
1376315446;	2;	5199.999204;	77.99998805999999;	1.5;	481280.0;	13979.733333333334;	0.0;	1.1333333333333333;	0.0;	0.0
1376315746;	2;	5199.999204;	77.99998805999999;	1.5;	481280.0;	12582.4;	0.0;	0.5333333333333333;	0.0;	0.0

===== 363.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.998608;	64.13331616533334;	1.2333333333333334;	702468.0;	11182.933333333332;	0.0;	0.8666666666666667;	0.0;	0.0
1376315146;	2;	5199.998608;	71.06664764266665;	1.3666666666666665;	702468.0;	30755.733333333334;	0.0;	0.4666666666666667;	0.0;	0.0
1376315446;	2;	5199.998608;	62.399983296;	1.2;	702468.0;	12582.4;	0.0;	1.1333333333333333;	0.0;	0.0
1376315746;	2;	5199.998608;	62.399983296;	1.2;	702468.0;	0.0;	0.0;	0.3333333333333333;	0.0;	0.0

===== 364.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	1;	2599.99945;	0.0;	0.0;	4069376.0;	0.0;	0.0;	0.06666666666666667;	0.0;	0.0
1376315146;	1;	2599.99945;	0.0;	0.0;	4069376.0;	36348.8;	0.0;	0.06666666666666667;	0.0;	0.0
1376315446;	1;	2599.99945;	0.0;	0.0;	4069376.0;	5592.0;	0.0;	0.26666666666666666;	0.0;	0.0
1376315746;	1;	2599.99945;	0.0;	0.0;	4069376.0;	39144.8;	0.0;	0.06666666666666667;	0.0;	0.0

===== 365.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0
1376315146;	0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0
1376315446;	0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0
1376315746;	0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0;	0.0

===== 366.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5851.998442;	156.05329178666668;	2.666666666666667;	8355840.0;	290804.26666666666;	0.0;	85.93333333333332;	9.333333333333334;	4.133333333333334
1376315146;	2;	5851.998442;	150.20129334466668;	2.566666666666667;	8355840.0;	218102.4;	0.0;	88.53333333333333;	9.2;	4.266666666666667
1376315446;	2;	5851.998442;	154.65995882428572;	2.642857142857143;	8355840.0;	185747.14285714287;	0.0;	91.14285714285714;	9.571428571428571;	4.5
1376315746;	2;	5851.998442;	177.51061940733334;	3.033333333333333;	8355840.0;	313172.8;	0.0;	94.33333333333331;	9.266666666666667;	4.333333333333333

===== 367.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5851.99808;	99.48396736000001;	1.7;	8355840.0;	167772.0;	0.0;	76.80000000000001;	10.4;	5.266666666666667
1376315146;	2;	5851.99808;	99.48396736000001;	1.7;	8355840.0;	89476.53333333334;	0.0;	79.53333333333332;	11.733333333333333;	5.4
1376315446;	2;	5851.99808;	93.63196928;	1.6;	8355840.0;	123031.2;	0.0;	75.86666666666666;	10.0;	5.466666666666667
1376315746;	2;	5851.99808;	95.58263530666669;	1.6333333333333335;	8355840.0;	162178.4;	0.0;	77.8;	11.133333333333333;	5.466666666666667

===== 368.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5851.998668;	85.82931379733333;	1.4666666666666666;	8347648.0;	78292.53333333334;	0.0;	10.333333333333334;	4.533333333333333;	0.06666666666666667
1376315146;	2;	5851.998668;	79.97731512933333;	1.3666666666666665;	8347648.0;	22369.066666666666;	0.0;	10.066666666666666;	4.266666666666667;	0.0
1376315446;	2;	5851.998668;	83.87864757466667;	1.4333333333333333;	8347648.0;	44738.13333333333;	0.0;	10.133333333333333;	4.533333333333333;	0.06666666666666667
1376315746;	2;	5851.998668;	79.97731512933333;	1.3666666666666665;	8347648.0;	100662.66666666667;	0.0;	9.8;	4.4;	0.0

===== 369.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.997978;	105.73329221933332;	2.033333333333333;	8364032.0;	162178.66666666666;	0.0;	73.13333333333333;	14.6;	8.4
1376315146;	2;	5199.997978;	103.99995956000001;	2.0;	8364032.0;	262841.6;	0.0;	74.53333333333333;	14.866666666666667;	8.533333333333333
1376315446;	2;	5199.997978;	105.73329221933332;	2.033333333333333;	8364032.0;	95069.06666666667;	0.0;	68.33333333333333;	13.733333333333333;	7.666666666666667
1376315746;	2;	5199.997978;	103.99995956000001;	2.0;	8364032.0;	257248.53333333333;	0.0;	68.26666666666667;	13.733333333333333;	7.8

===== 37.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	1;	2925.999494;	5.851998988;	0.2;	2097152.0;	82485.86666666667;	0.0;	13.4;	0.0;	0.0
1376315146;	1;	2925.999494;	3.901332658666667;	0.13333333333333333;	2097152.0;	89476.53333333334;	0.0;	0.6;	0.0;	0.0
1376315446;	1;	2925.999494;	7.802665317333334;	0.26666666666666666;	2097152.0;	95069.06666666667;	0.0;	0.0;	0.0;	0.0
1376315746;	1;	2925.999494;	0.0;	0.0;	2097152.0;	69902.66666666667;	0.0;	0.0;	0.0;	0.0

===== 370.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.999204;	112.66664942;	2.1666666666666665;	8357888.0;	268434.4;	0.13333333333333333;	79.73333333333333;	11.666666666666666;	5.733333333333333
1376315146;	2;	5199.999204;	107.46665021599998;	2.0666666666666664;	8357888.0;	201326.4;	0.0;	76.33333333333333;	10.933333333333334;	5.0
1376315446;	2;	5199.999204;	109.19998328399998;	2.1;	8357888.0;	234879.2;	0.0;	76.46666666666667;	11.4;	5.2
1376315746;	2;	5199.999204;	109.19998328399998;	2.1;	8357888.0;	134216.8;	0.0;	72.2;	10.733333333333333;	5.133333333333334

===== 371.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.99925;	95.33331958333333;	1.8333333333333335;	8359936.0;	78291.73333333334;	0.0;	18.06666666666667;	5.133333333333334;	0.2
1376315146;	2;	5199.99925;	98.79998574999999;	1.9;	8359936.0;	72701.06666666667;	0.0;	18.0;	5.0;	0.13333333333333333
1376315446;	2;	5199.99925;	100.53331883333333;	1.9333333333333333;	8359936.0;	117438.4;	0.0;	17.933333333333334;	5.133333333333334;	0.2
1376315746;	2;	5199.99925;	97.06665266666666;	1.8666666666666665;	8359936.0;	106254.13333333333;	0.0;	17.800000000000004;	5.0;	0.2

===== 372.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.998594;	123.06663339133333;	2.3666666666666667;	8357888.0;	83885.06666666667;	0.0;	9.933333333333334;	4.6;	0.0
1376315146;	2;	5199.998594;	121.33330052666666;	2.3333333333333335;	8357888.0;	50331.2;	0.0;	10.133333333333333;	4.666666666666667;	0.0
1376315446;	2;	5199.998594;	117.86663479733332;	2.2666666666666666;	8357888.0;	39145.86666666667;	0.0;	10.133333333333333;	4.6;	0.0
1376315746;	2;	5199.998594;	121.33330052666666;	2.3333333333333335;	8357888.0;	139808.53333333333;	0.0;	10.266666666666667;	4.533333333333333;	0.0

===== 373.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.998602;	83.19997763199999;	1.6;	8357888.0;	150994.4;	0.0;	10.066666666666666;	4.6;	0.0
1376315146;	2;	5199.998602;	88.399976234;	1.7;	8357888.0;	173364.0;	0.0;	9.933333333333334;	4.666666666666667;	0.0
1376315446;	2;	5199.998602;	86.66664336666665;	1.6666666666666665;	8357888.0;	106254.66666666667;	0.0;	10.333333333333334;	4.666666666666667;	0.0
1376315746;	2;	5199.998602;	83.19997763199999;	1.6;	8357888.0;	50330.4;	0.0;	10.066666666666666;	4.533333333333333;	0.0

===== 374.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.998686;	107.46663951066665;	2.0666666666666664;	8364032.0;	150994.4;	0.0;	10.0;	4.6;	0.0
1376315146;	2;	5199.998686;	109.199972406;	2.1;	8364032.0;	61514.933333333334;	0.0;	9.933333333333334;	4.666666666666667;	0.0
1376315446;	2;	5199.998686;	109.199972406;	2.1;	8364032.0;	55922.666666666664;	0.0;	10.066666666666666;	4.666666666666667;	0.0
1376315746;	2;	5199.998686;	109.199972406;	2.1;	8364032.0;	16776.8;	0.0;	9.733333333333333;	4.6;	0.0

===== 375.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.998578;	79.73331152933333;	1.5333333333333334;	8359936.0;	240472.26666666666;	0.0;	9.533333333333333;	4.6;	0.0
1376315146;	2;	5199.998578;	83.199977248;	1.6;	8359936.0;	83885.6;	0.0;	9.733333333333334;	4.6;	0.0
1376315446;	2;	5199.998578;	83.199977248;	1.6;	8359936.0;	150992.8;	0.0;	9.466666666666667;	4.6;	0.0
1376315746;	2;	5199.998578;	84.93331010733334;	1.6333333333333335;	8359936.0;	150993.6;	0.0;	9.466666666666667;	4.533333333333333;	0.0

===== 376.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.999264;	77.99998896;	1.5;	8357888.0;	95069.86666666667;	0.0;	9.600000000000001;	4.666666666666667;	0.0
1376315146;	2;	5199.999264;	81.466655136;	1.5666666666666667;	8357888.0;	150994.4;	0.0;	9.6;	4.6;	0.0
1376315446;	2;	5199.999264;	83.19998822400001;	1.6;	8357888.0;	195732.53333333333;	0.0;	9.666666666666666;	4.666666666666667;	0.0
1376315746;	2;	5199.999264;	83.19998822400001;	1.6;	8357888.0;	184548.8;	0.0;	9.266666666666666;	4.6;	0.0

===== 377.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.99926;	77.99998889999999;	1.5;	8359936.0;	123031.73333333334;	0.0;	9.666666666666668;	4.666666666666667;	0.0
1376315146;	2;	5199.99926;	79.73332198666667;	1.5333333333333334;	8359936.0;	123032.0;	0.0;	9.533333333333333;	4.6;	0.0
1376315446;	2;	5199.99926;	81.46665507333333;	1.5666666666666667;	8359936.0;	123032.26666666666;	0.0;	9.933333333333334;	4.666666666666667;	0.0
1376315746;	2;	5199.99926;	83.19998815999999;	1.6;	8359936.0;	123030.93333333333;	0.0;	9.666666666666668;	4.6;	0.0

===== 378.csv =====
Timestamp [ms];	CPU cores;	CPU capacity provisioned [MHZ];	CPU usage [MHZ];	CPU usage [%];	Memory capacity provisioned [KB];	Memory usage [KB];	Disk read throughput [KB/s];	Disk write throughput [KB/s];	Network received throughput [KB/s];	Network transmitted throughput [KB/s]
1376314846;	2;	5199.998642;	76.26664674933332;	1.4666666666666666;	8359936.0;	167770.4;	0.0;	9.933333333333334;	4.533333333333333;	0.0
1376315146;	2;	5199.998642;	79.73331251066666;	1.5333333333333334;	8359936.0;	95069.33333333333;	0.0;	9.933333333333334;	4.666666666666667;	0.0
1376315446;	2;	5199.998642;	76.26664674933332;	1.4666666666666666;	8359936.0;	67107.2;	0.0;	9.866666666666667;	4.6;	0.0

In [ ]:
text_files = [
    f for f in bitbrains_files
    if f.suffix.lower() in [".txt", ".tsv"]
]

if text_files:
    for file in text_files:
        print(f"\n===== {file.name} =====")

        with open(file, "r", encoding="utf-8", errors="ignore") as f:
            for _ in range(10):
                print(f.readline().strip())
else:
    print("No TXT/TSV files found.")

No TXT/TSV files found.

In [ ]:
if not csv_files:
    raise FileNotFoundError("No CSV file found.")

if len(csv_files) == 1:
    BITBRAINS_FILE = csv_files[0]
else:
    print("Multiple CSV files found:")
    for i, file in enumerate(csv_files):
        print(i, file.name)

    # Change this index if needed
    BITBRAINS_FILE = csv_files[0]

print("Loading:", BITBRAINS_FILE.name)

bitbrains_df = pd.read_csv(
    BITBRAINS_FILE,
    low_memory=False
)

print("Loaded successfully.")
print("Shape:", bitbrains_df.shape)

Multiple CSV files found:
0 1.csv
1 10.csv
2 100.csv
3 1000.csv
4 1001.csv
5 1002.csv
6 1003.csv
7 1004.csv
8 1005.csv
9 1006.csv
10 1007.csv
11 1008.csv
12 1009.csv
13 101.csv
14 1010.csv
15 1011.csv
16 1012.csv
17 1013.csv
18 1014.csv
19 1015.csv
20 1016.csv
21 1017.csv
22 1018.csv
23 1019.csv
24 102.csv
25 1020.csv
26 1021.csv
27 1022.csv
28 1023.csv
29 1024.csv
30 1025.csv
31 1026.csv
32 1027.csv
33 1028.csv
34 1029.csv
35 103.csv
36 1030.csv
37 1031.csv
38 1032.csv
39 1033.csv
40 1034.csv
41 1035.csv
42 1036.csv
43 1037.csv
44 1038.csv
45 1039.csv
46 104.csv
47 1040.csv
48 1041.csv
49 1042.csv
50 1043.csv
51 1044.csv
52 1045.csv
53 1046.csv
54 1047.csv
55 1048.csv
56 1049.csv
57 105.csv
58 1050.csv
59 1051.csv
60 1052.csv
61 1053.csv
62 1054.csv
63 1055.csv
64 1056.csv
65 1057.csv
66 1058.csv
67 1059.csv
68 106.csv
69 1060.csv
70 1061.csv
71 1062.csv
72 1063.csv
73 1064.csv
74 1065.csv
75 1066.csv
76 1067.csv
77 1068.csv
78 1069.csv
79 107.csv
80 1070.csv
81 1071.csv
82 1072.csv
83 1073.csv
84 1074.csv
85 1075.csv
86 1076.csv
87 1077.csv
88 1078.csv
89 1079.csv
90 108.csv
91 1080.csv
92 1081.csv
93 1082.csv
94 1083.csv
95 1084.csv
96 1085.csv
97 1086.csv
98 1087.csv
99 1088.csv
100 1089.csv
101 109.csv
102 1090.csv
103 1091.csv
104 1092.csv
105 1093.csv
106 1094.csv
107 1095.csv
108 1096.csv
109 1097.csv
110 1098.csv
111 1099.csv
112 11.csv
113 110.csv
114 1100.csv
115 1101.csv
116 1102.csv
117 1103.csv
118 1104.csv
119 1105.csv
120 1106.csv
121 1107.csv
122 1108.csv
123 1109.csv
124 111.csv
125 1110.csv
126 1111.csv
127 1112.csv
128 1113.csv
129 1114.csv
130 1115.csv
131 1116.csv
132 1117.csv
133 1118.csv
134 1119.csv
135 112.csv
136 1120.csv
137 1121.csv
138 1122.csv
139 1123.csv
140 1124.csv
141 1125.csv
142 1126.csv
143 1127.csv
144 1128.csv
145 1129.csv
146 113.csv
147 1130.csv
148 1131.csv
149 1132.csv
150 1133.csv
151 1134.csv
152 1135.csv
153 1136.csv
154 1137.csv
155 1138.csv
156 1139.csv
157 114.csv
158 1140.csv
159 1141.csv
160 1142.csv
161 1143.csv
162 1144.csv
163 1145.csv
164 1146.csv
165 1147.csv
166 1148.csv
167 1149.csv
168 115.csv
169 1150.csv
170 1151.csv
171 1152.csv
172 1153.csv
173 1154.csv
174 1155.csv
175 1156.csv
176 1157.csv
177 1158.csv
178 1159.csv
179 116.csv
180 1160.csv
181 1161.csv
182 1162.csv
183 1163.csv
184 1164.csv
185 1165.csv
186 1166.csv
187 1167.csv
188 1168.csv
189 1169.csv
190 117.csv
191 1170.csv
192 1171.csv
193 1172.csv
194 1173.csv
195 1174.csv
196 1175.csv
197 1176.csv
198 1177.csv
199 1178.csv
200 1179.csv
201 118.csv
202 1180.csv
203 1181.csv
204 1182.csv
205 1183.csv
206 1184.csv
207 1185.csv
208 1186.csv
209 1187.csv
210 1188.csv
211 1189.csv
212 119.csv
213 1190.csv
214 1191.csv
215 1192.csv
216 1193.csv
217 1194.csv
218 1195.csv
219 1196.csv
220 1197.csv
221 1198.csv
222 1199.csv
223 12.csv
224 120.csv
225 1200.csv
226 1201.csv
227 1202.csv
228 1203.csv
229 1204.csv
230 1205.csv
231 1206.csv
232 1207.csv
233 1208.csv
234 1209.csv
235 121.csv
236 1210.csv
237 1211.csv
238 1212.csv
239 1213.csv
240 1214.csv
241 1215.csv
242 1216.csv
243 1217.csv
244 1218.csv
245 1219.csv
246 122.csv
247 1220.csv
248 1221.csv
249 1222.csv
250 1223.csv
251 1224.csv
252 1225.csv
253 1226.csv
254 1227.csv
255 1228.csv
256 1229.csv
257 123.csv
258 1230.csv
259 1231.csv
260 1232.csv
261 1233.csv
262 1234.csv
263 1235.csv
264 1236.csv
265 1237.csv
266 1238.csv
267 1239.csv
268 124.csv
269 1240.csv
270 1241.csv
271 1242.csv
272 1243.csv
273 1244.csv
274 1245.csv
275 1246.csv
276 1247.csv
277 1248.csv
278 1249.csv
279 125.csv
280 1250.csv
281 126.csv
282 127.csv
283 128.csv
284 129.csv
285 13.csv
286 130.csv
287 131.csv
288 132.csv
289 133.csv
290 134.csv
291 135.csv
292 136.csv
293 137.csv
294 138.csv
295 139.csv
296 14.csv
297 140.csv
298 141.csv
299 142.csv
300 143.csv
301 144.csv
302 145.csv
303 146.csv
304 147.csv
305 148.csv
306 149.csv
307 15.csv
308 150.csv
309 151.csv
310 152.csv
311 153.csv
312 154.csv
313 155.csv
314 156.csv
315 157.csv
316 158.csv
317 159.csv
318 16.csv
319 160.csv
320 161.csv
321 162.csv
322 163.csv
323 164.csv
324 165.csv
325 166.csv
326 167.csv
327 168.csv
328 169.csv
329 17.csv
330 170.csv
331 171.csv
332 172.csv
333 173.csv
334 174.csv
335 175.csv
336 176.csv
337 177.csv
338 178.csv
339 179.csv
340 18.csv
341 180.csv
342 181.csv
343 182.csv
344 183.csv
345 184.csv
346 185.csv
347 186.csv
348 187.csv
349 188.csv
350 189.csv
351 19.csv
352 190.csv
353 191.csv
354 192.csv
355 193.csv
356 194.csv
357 195.csv
358 196.csv
359 197.csv
360 198.csv
361 199.csv
362 2.csv
363 20.csv
364 200.csv
365 201.csv
366 202.csv
367 203.csv
368 204.csv
369 205.csv
370 206.csv
371 207.csv
372 208.csv
373 209.csv
374 21.csv
375 210.csv
376 211.csv
377 212.csv
378 213.csv
379 214.csv
380 215.csv
381 216.csv
382 217.csv
383 218.csv
384 219.csv
385 22.csv
386 220.csv
387 221.csv
388 222.csv
389 223.csv
390 224.csv
391 225.csv
392 226.csv
393 227.csv
394 228.csv
395 229.csv
396 23.csv
397 230.csv
398 231.csv
399 232.csv
400 233.csv
401 234.csv
402 235.csv
403 236.csv
404 237.csv
405 238.csv
406 239.csv
407 24.csv
408 240.csv
409 241.csv
410 242.csv
411 243.csv
412 244.csv
413 245.csv
414 246.csv
415 247.csv
416 248.csv
417 249.csv
418 25.csv
419 250.csv
420 251.csv
421 252.csv
422 253.csv
423 254.csv
424 255.csv
425 256.csv
426 257.csv
427 258.csv
428 259.csv
429 26.csv
430 260.csv
431 261.csv
432 262.csv
433 263.csv
434 264.csv
435 265.csv
436 266.csv
437 267.csv
438 268.csv
439 269.csv
440 27.csv
441 270.csv
442 271.csv
443 272.csv
444 273.csv
445 274.csv
446 275.csv
447 276.csv
448 277.csv
449 278.csv
450 279.csv
451 28.csv
452 280.csv
453 281.csv
454 282.csv
455 283.csv
456 284.csv
457 285.csv
458 286.csv
459 287.csv
460 288.csv
461 289.csv
462 29.csv
463 290.csv
464 291.csv
465 292.csv
466 293.csv
467 294.csv
468 295.csv
469 296.csv
470 297.csv
471 298.csv
472 299.csv
473 3.csv
474 30.csv
475 300.csv
476 301.csv
477 302.csv
478 303.csv
479 304.csv
480 305.csv
481 306.csv
482 307.csv
483 308.csv
484 309.csv
485 31.csv
486 310.csv
487 311.csv
488 312.csv
489 313.csv
490 314.csv
491 315.csv
492 316.csv
493 317.csv
494 318.csv
495 319.csv
496 32.csv
497 320.csv
498 321.csv
499 322.csv
500 323.csv
501 324.csv
502 325.csv
503 326.csv
504 327.csv
505 328.csv
506 329.csv
507 33.csv
508 330.csv
509 331.csv
510 332.csv
511 333.csv
512 334.csv
513 335.csv
514 336.csv
515 337.csv
516 338.csv
517 339.csv
518 34.csv
519 340.csv
520 341.csv
521 342.csv
522 343.csv
523 344.csv
524 345.csv
525 346.csv
526 347.csv
527 348.csv
528 349.csv
529 35.csv
530 350.csv
531 351.csv
532 352.csv
533 353.csv
534 354.csv
535 355.csv
536 356.csv
537 357.csv
538 358.csv
539 359.csv
540 36.csv
541 360.csv
542 361.csv
543 362.csv
544 363.csv
545 364.csv
546 365.csv
547 366.csv
548 367.csv
549 368.csv
550 369.csv
551 37.csv
552 370.csv
553 371.csv
554 372.csv
555 373.csv
556 374.csv
557 375.csv
558 376.csv
559 377.csv
560 378.csv
561 379.csv
562 38.csv
563 380.csv
564 381.csv
565 382.csv
566 383.csv
567 384.csv
568 385.csv
569 386.csv
570 387.csv
571 388.csv
572 389.csv
573 39.csv
574 390.csv
575 391.csv
576 392.csv
577 393.csv
578 394.csv
579 395.csv
580 396.csv
581 397.csv
582 398.csv
583 399.csv
584 4.csv
585 40.csv
586 400.csv
587 401.csv
588 402.csv
589 403.csv
590 404.csv
591 405.csv
592 406.csv
593 407.csv
594 408.csv
595 409.csv
596 41.csv
597 410.csv
598 411.csv
599 412.csv
600 413.csv
601 414.csv
602 415.csv
603 416.csv
604 417.csv
605 418.csv
606 419.csv
607 42.csv
608 420.csv
609 421.csv
610 422.csv
611 423.csv
612 424.csv
613 425.csv
614 426.csv
615 427.csv
616 428.csv
617 429.csv
618 43.csv
619 430.csv
620 431.csv
621 432.csv
622 433.csv
623 434.csv
624 435.csv
625 436.csv
626 437.csv
627 438.csv
628 439.csv
629 44.csv
630 440.csv
631 441.csv
632 442.csv
633 443.csv
634 444.csv
635 445.csv
636 446.csv
637 447.csv
638 448.csv
639 449.csv
640 45.csv
641 450.csv
642 451.csv
643 452.csv
644 453.csv
645 454.csv
646 455.csv
647 456.csv
648 457.csv
649 458.csv
650 459.csv
651 46.csv
652 460.csv
653 461.csv
654 462.csv
655 463.csv
656 464.csv
657 465.csv
658 466.csv
659 467.csv
660 468.csv
661 469.csv
662 47.csv
663 470.csv
664 471.csv
665 472.csv
666 473.csv
667 474.csv
668 475.csv
669 476.csv
670 477.csv
671 478.csv
672 479.csv
673 48.csv
674 480.csv
675 481.csv
676 482.csv
677 483.csv
678 484.csv
679 485.csv
680 486.csv
681 487.csv
682 488.csv
683 489.csv
684 49.csv
685 490.csv
686 491.csv
687 492.csv
688 493.csv
689 494.csv
690 495.csv
691 496.csv
692 497.csv
693 498.csv
694 499.csv
695 5.csv
696 50.csv
697 500.csv
698 501.csv
699 502.csv
700 503.csv
701 504.csv
702 505.csv
703 506.csv
704 507.csv
705 508.csv
706 509.csv
707 51.csv
708 510.csv
709 511.csv
710 512.csv
711 513.csv
712 514.csv
713 515.csv
714 516.csv
715 517.csv
716 518.csv
717 519.csv
718 52.csv
719 520.csv
720 521.csv
721 522.csv
722 523.csv
723 524.csv
724 525.csv
725 526.csv
726 527.csv
727 528.csv
728 529.csv
729 53.csv
730 530.csv
731 531.csv
732 532.csv
733 533.csv
734 534.csv
735 535.csv
736 536.csv
737 537.csv
738 538.csv
739 539.csv
740 54.csv
741 540.csv
742 541.csv
743 542.csv
744 543.csv
745 544.csv
746 545.csv
747 546.csv
748 547.csv
749 548.csv
750 549.csv
751 55.csv
752 550.csv
753 551.csv
754 552.csv
755 553.csv
756 554.csv
757 555.csv
758 556.csv
759 557.csv
760 558.csv
761 559.csv
762 56.csv
763 560.csv
764 561.csv
765 562.csv
766 563.csv
767 564.csv
768 565.csv
769 566.csv
770 567.csv
771 568.csv
772 569.csv
773 57.csv
774 570.csv
775 571.csv
776 572.csv
777 573.csv
778 574.csv
779 575.csv
780 576.csv
781 577.csv
782 578.csv
783 579.csv
784 58.csv
785 580.csv
786 581.csv
787 582.csv
788 583.csv
789 584.csv
790 585.csv
791 586.csv
792 587.csv
793 588.csv
794 589.csv
795 59.csv
796 590.csv
797 591.csv
798 592.csv
799 593.csv
800 594.csv
801 595.csv
802 596.csv
803 597.csv
804 598.csv
805 599.csv
806 6.csv
807 60.csv
808 600.csv
809 601.csv
810 602.csv
811 603.csv
812 604.csv
813 605.csv
814 606.csv
815 607.csv
816 608.csv
817 609.csv
818 61.csv
819 610.csv
820 611.csv
821 612.csv
822 613.csv
823 614.csv
824 615.csv
825 616.csv
826 617.csv
827 618.csv
828 619.csv
829 62.csv
830 620.csv
831 621.csv
832 622.csv
833 623.csv
834 624.csv
835 625.csv
836 626.csv
837 627.csv
838 628.csv
839 629.csv
840 63.csv
841 630.csv
842 631.csv
843 632.csv
844 633.csv
845 634.csv
846 635.csv
847 636.csv
848 637.csv
849 638.csv
850 639.csv
851 64.csv
852 640.csv
853 641.csv
854 642.csv
855 643.csv
856 644.csv
857 645.csv
858 646.csv
859 647.csv
860 648.csv
861 649.csv
862 65.csv
863 650.csv
864 651.csv
865 652.csv
866 653.csv
867 654.csv
868 655.csv
869 656.csv
870 657.csv
871 658.csv
872 659.csv
873 66.csv
874 660.csv
875 661.csv
876 662.csv
877 663.csv
878 664.csv
879 665.csv
880 666.csv
881 667.csv
882 668.csv
883 669.csv
884 67.csv
885 670.csv
886 671.csv
887 672.csv
888 673.csv
889 674.csv
890 675.csv
891 676.csv
892 677.csv
893 678.csv
894 679.csv
895 68.csv
896 680.csv
897 681.csv
898 682.csv
899 683.csv
900 684.csv
901 685.csv
902 686.csv
903 687.csv
904 688.csv
905 689.csv
906 69.csv
907 690.csv
908 691.csv
909 692.csv
910 693.csv
911 694.csv
912 695.csv
913 696.csv
914 697.csv
915 698.csv
916 699.csv
917 7.csv
918 70.csv
919 700.csv
920 701.csv
921 702.csv
922 703.csv
923 704.csv
924 705.csv
925 706.csv
926 707.csv
927 708.csv
928 709.csv
929 71.csv
930 710.csv
931 711.csv
932 712.csv
933 713.csv
934 714.csv
935 715.csv
936 716.csv
937 717.csv
938 718.csv
939 719.csv
940 72.csv
941 720.csv
942 721.csv
943 722.csv
944 723.csv
945 724.csv
946 725.csv
947 726.csv
948 727.csv
949 728.csv
950 729.csv
951 73.csv
952 730.csv
953 731.csv
954 732.csv
955 733.csv
956 734.csv
957 735.csv
958 736.csv
959 737.csv
960 738.csv
961 739.csv
962 74.csv
963 740.csv
964 741.csv
965 742.csv
966 743.csv
967 744.csv
968 745.csv
969 746.csv
970 747.csv
971 748.csv
972 749.csv
973 75.csv
974 750.csv
975 751.csv
976 752.csv
977 753.csv
978 754.csv
979 755.csv
980 756.csv
981 757.csv
982 758.csv
983 759.csv
984 76.csv
985 760.csv
986 761.csv
987 762.csv
988 763.csv
989 764.csv
990 765.csv
991 766.csv
992 767.csv
993 768.csv
994 769.csv
995 77.csv
996 770.csv
997 771.csv
998 772.csv
999 773.csv
1000 774.csv
1001 775.csv
1002 776.csv
1003 777.csv
1004 778.csv
1005 779.csv
1006 78.csv
1007 780.csv
1008 781.csv
1009 782.csv
1010 783.csv
1011 784.csv
1012 785.csv
1013 786.csv
1014 787.csv
1015 788.csv
1016 789.csv
1017 79.csv
1018 790.csv
1019 791.csv
1020 792.csv
1021 793.csv
1022 794.csv
1023 795.csv
1024 796.csv
1025 797.csv
1026 798.csv
1027 799.csv
1028 8.csv
1029 80.csv
1030 800.csv
1031 801.csv
1032 802.csv
1033 803.csv
1034 804.csv
1035 805.csv
1036 806.csv
1037 807.csv
1038 808.csv
1039 809.csv
1040 81.csv
1041 810.csv
1042 811.csv
1043 812.csv
1044 813.csv
1045 814.csv
1046 815.csv
1047 816.csv
1048 817.csv
1049 818.csv
1050 819.csv
1051 82.csv
1052 820.csv
1053 821.csv
1054 822.csv
1055 823.csv
1056 824.csv
1057 825.csv
1058 826.csv
1059 827.csv
1060 828.csv
1061 829.csv
1062 83.csv
1063 830.csv
1064 831.csv
1065 832.csv
1066 833.csv
1067 834.csv
1068 835.csv
1069 836.csv
1070 837.csv
1071 838.csv
1072 839.csv
1073 84.csv
1074 840.csv
1075 841.csv
1076 842.csv
1077 843.csv
1078 844.csv
1079 845.csv
1080 846.csv
1081 847.csv
1082 848.csv
1083 849.csv
1084 85.csv
1085 850.csv
1086 851.csv
1087 852.csv
1088 853.csv
1089 854.csv
1090 855.csv
1091 856.csv
1092 857.csv
1093 858.csv
1094 859.csv
1095 86.csv
1096 860.csv
1097 861.csv
1098 862.csv
1099 863.csv
1100 864.csv
1101 865.csv
1102 866.csv
1103 867.csv
1104 868.csv
1105 869.csv
1106 87.csv
1107 870.csv
1108 871.csv
1109 872.csv
1110 873.csv
1111 874.csv
1112 875.csv
1113 876.csv
1114 877.csv
1115 878.csv
1116 879.csv
1117 88.csv
1118 880.csv
1119 881.csv
1120 882.csv
1121 883.csv
1122 884.csv
1123 885.csv
1124 886.csv
1125 887.csv
1126 888.csv
1127 889.csv
1128 89.csv
1129 890.csv
1130 891.csv
1131 892.csv
1132 893.csv
1133 894.csv
1134 895.csv
1135 896.csv
1136 897.csv
1137 898.csv
1138 899.csv
1139 9.csv
1140 90.csv
1141 900.csv
1142 901.csv
1143 902.csv
1144 903.csv
1145 904.csv
1146 905.csv
1147 906.csv
1148 907.csv
1149 908.csv
1150 909.csv
1151 91.csv
1152 910.csv
1153 911.csv
1154 912.csv
1155 913.csv
1156 914.csv
1157 915.csv
1158 916.csv
1159 917.csv
1160 918.csv
1161 919.csv
1162 92.csv
1163 920.csv
1164 921.csv
1165 922.csv
1166 923.csv
1167 924.csv
1168 925.csv
1169 926.csv
1170 927.csv
1171 928.csv
1172 929.csv
1173 93.csv
1174 930.csv
1175 931.csv
1176 932.csv
1177 933.csv
1178 934.csv
1179 935.csv
1180 936.csv
1181 937.csv
1182 938.csv
1183 939.csv
1184 94.csv
1185 940.csv
1186 941.csv
1187 942.csv
1188 943.csv
1189 944.csv
1190 945.csv
1191 946.csv
1192 947.csv
1193 948.csv
1194 949.csv
1195 95.csv
1196 950.csv
1197 951.csv
1198 952.csv
1199 953.csv
1200 954.csv
1201 955.csv
1202 956.csv
1203 957.csv
1204 958.csv
1205 959.csv
1206 96.csv
1207 960.csv
1208 961.csv
1209 962.csv
1210 963.csv
1211 964.csv
1212 965.csv
1213 966.csv
1214 967.csv
1215 968.csv
1216 969.csv
1217 97.csv
1218 970.csv
1219 971.csv
1220 972.csv
1221 973.csv
1222 974.csv
1223 975.csv
1224 976.csv
1225 977.csv
1226 978.csv
1227 979.csv
1228 98.csv
1229 980.csv
1230 981.csv
1231 982.csv
1232 983.csv
1233 984.csv
1234 985.csv
1235 986.csv
1236 987.csv
1237 988.csv
1238 989.csv
1239 99.csv
1240 990.csv
1241 991.csv
1242 992.csv
1243 993.csv
1244 994.csv
1245 995.csv
1246 996.csv
1247 997.csv
1248 998.csv
1249 999.csv
Loading: 1.csv
Loaded successfully.
Shape: (8634, 1)

In [ ]:
display(bitbrains_df.head())

  Timestamp [ms];\tCPU cores;\tCPU capacity provisioned [MHZ];\tCPU usage [MHZ];\tCPU usage [%];\tMemory capacity provisioned [KB];\tMemory usage [KB];\tDisk read throughput [KB/s];\tDisk write throughput [KB/s];\tNetwork received throughput [KB/s];\tNetwork transmitted throughput [KB/s]
0  1376314846;\t4;\t11703.99824;\t10912.027692426...
1  1376315146;\t4;\t11703.99824;\t10890.57036232;...
2  1376315446;\t4;\t11703.99824;\t10434.11443096;...
3  1376315746;\t4;\t11703.99824;\t10539.450415120...
4  1376316046;\t4;\t11703.99824;\t10951.041019893...

In [ ]:
# Reload BitBrains using the correct delimiter
BITBRAINS_FILE = bitbrains_files[0]

print("Loading:", BITBRAINS_FILE.name)

bitbrains_df = pd.read_csv(
    BITBRAINS_FILE,
    sep=";\t",
    engine="python"
)

print("Loaded successfully.")
print("Shape:", bitbrains_df.shape)

Loading: 1234.csv
Loaded successfully.
Shape: (5754, 11)